<?php
// database/migrations/seed_all_pages_content.php — Master seed script for all content blocks
require_once __DIR__ . '/../../includes/db.php';
$pdo = get_db();

// 1. Clean up duplicate slug if present
$pdo->exec("DELETE FROM pages WHERE slug = 'quality-compliance'");

// 2. Ensure all standard pages exist
$pagesList = [
    ['home', 'Home', 'Prince Art Packages — Pharmaceutical Secondary Packaging Manufacturer', 'ISO 9001:2015 & FSC certified pharmaceutical secondary packaging manufacturer in Karachi, Pakistan.'],
    ['about', 'About Us', 'About Prince Art Packages | cGMP Pharma Packaging Manufacturer', 'Formerly Prince Art Press — ISO 9001:2015 & FSC certified manufacturer operating two plants in Korangi Creek Industrial Park, Karachi.'],
    ['products', 'Products', 'Pharmaceutical Secondary Packaging Products | Prince Art Packages', 'Printed cartons, leaf-inserts, printed labels, honeycomb separators, pill-folders, tamper-evident, 3D-ENGRAVIX and ColdSeal wallets.'],
    ['capabilities', 'Capabilities', 'Manufacturing Capabilities & Production Capacity | Prince Art Packages', 'Integrated multi-stage production flow for high-volume pharmaceutical packaging.'],
    ['innovation', 'Innovation & Technology', 'Innovation | Prince Art Packages', 'ColdSeal Blister Wallet and 3D-Engravix anti-counterfeit technology.'],
    ['quality', 'Quality & Compliance', 'Quality Certifications & In-House Laboratory | Prince Art Packages', 'ISO 9001:2015 (KQ.2025.5393), FSC Chain of Custody (RR-COC-003348) and cGMP compliant with in-house lab testing.'],
    ['industries', 'Industries We Serve', 'Industries We Serve | Pharma, Healthcare & Biologics Packaging', 'Specialized secondary packaging for commercial pharmaceuticals, healthcare/OTC, and biologics & medical devices.'],
    ['case-studies', 'Case Studies', 'Case Studies & Manufacturing Results | Prince Art Packages', 'Client performance highlights illustrating zero-defect delivery standards for pharmaceutical clients.'],
    ['blog', 'Blog', 'Pharmaceutical Packaging Insights & Technical Articles', 'Technical publications and regulatory compliance guidelines from Prince Art Packages.'],
    ['contact', 'Contact / Request a Quote', 'Contact Us | Prince Art Packages', 'Get in touch with Prince Art Packages for technical quotations and plant audit requests.'],
    ['privacy', 'Privacy Policy', 'Privacy Policy | Prince Art Packages', 'Privacy Policy for princeartpackages.com.'],
    ['terms', 'Terms & Conditions', 'Terms & Conditions | Prince Art Packages', 'Terms & Conditions for princeartpackages.com.']
];

$stmtPage = $pdo->prepare("INSERT INTO pages (slug, title, meta_title, meta_description) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE title = VALUES(title)");
foreach ($pagesList as $p) {
    $stmtPage->execute($p);
}

// 3. Define all blocks for all pages
$allBlocks = [
    'home' => [
        ['hero_title', 'text', 'Precision Pharmaceutical Secondary Packaging Engineered for Global Audit Compliance', 10],
        ['hero_subtitle', 'text', 'ISO 9001:2015 certified manufacturer of printed cartons, leaf-inserts, printed labels, ColdSeal blister wallets, and 3D-Engravix™ optical anti-counterfeit security packaging based in Korangi Creek Industrial Park, Karachi.', 20],
        ['hero_image', 'image', 'assets/images/engravix.jpg', 25],
        ['trust_1_title', 'text', 'ISO 9001:2015 Certified', 30],
        ['trust_1_text', 'text', 'Cert No. KQ.2025.5393 (ASCERT)', 35],
        ['trust_2_title', 'text', 'FSC Chain of Custody', 40],
        ['trust_2_text', 'text', 'Cert No. RR-COC-003348 (FSC-C222205)', 45],
        ['trust_3_title', 'text', 'cGMP Compliant', 50],
        ['trust_3_text', 'text', 'Strict Line Clearance & QA', 55],
        ['trust_5_title', 'text', 'WHO-GMP Compliant', 56],
        ['trust_5_text', 'text', 'Manufacturing Standards', 58],
        ['trust_4_title', 'text', 'Unit 1 & Unit 2 Plants', 60],
        ['trust_4_text', 'text', 'Korangi Creek Industrial Park', 65],
        ['values_subtitle', 'text', 'Supporting Value Points', 66],
        ['values_title', 'text', 'Engineered for Compliance & Pharmaceutical Precision', 67],
        ['values_intro', 'text', 'As a dedicated pharmaceutical secondary packaging partner, Prince Art Packages operates under strict cGMP and ISO 9001:2015 standards across two state-of-the-art facilities in Korangi Creek Industrial Park, Karachi. We deliver audited packaging integrity designed to meet rigorous global regulatory audits.', 68],
        ['value_1_title', 'text', 'Pharmaceutical Expertise', 69],
        ['value_1_text', 'text', 'Specialized secondary packaging solutions for pharmaceutical products.', 70],
        ['value_2_title', 'text', 'Compliance Focused', 71],
        ['value_2_text', 'text', 'Packaging manufactured with quality and regulatory requirements in mind.', 72],
        ['value_3_title', 'text', 'Precision Manufacturing', 73],
        ['value_3_text', 'text', 'Controlled production processes for consistent packaging quality.', 74],
        ['value_4_title', 'text', 'Custom Solutions', 75],
        ['value_4_text', 'text', 'Packaging engineered according to product and customer requirements.', 76],
        ['capability_subtitle', 'text', 'Manufacturing Capabilities', 80],
        ['capability_title', 'text', 'Comprehensive Pharmaceutical Packaging Solutions', 85],
        ['capability_intro', 'text', 'Purpose-engineered paperboard packaging, precision inserts, self-adhesive roll labels, and proprietary security features.', 80],
        ['feat_1_title', 'text', 'Printed Cartons', 85],
        ['feat_1_text', 'text', 'Reverse tuck, crash lock, tamper-evident, and child-resistant cartons printed on food & pharma-grade virgin board.', 90],
        ['feat_1_image', 'image', 'assets/images/prod_cartons.jpg', 91],
        ['feat_2_title', 'text', 'Leaf-Inserts', 95],
        ['feat_2_text', 'text', 'Ultra-thin 27gsm to 60gsm prescribing information inserts, cross-folded or miniature outserts for automated packaging lines.', 100],
        ['feat_2_image', 'image', 'assets/images/prod_leaflets.jpg', 101],
        ['feat_3_title', 'text', 'Printed Labels & Tamper-Evident', 105],
        ['feat_3_text', 'text', 'Self-adhesive roll labels for vials, bottles, ampoules, and destructible tamper-evident security seals with 2D barcode serialization.', 110],
        ['feat_3_image', 'image', 'assets/images/prod_labels.jpg', 111],
        ['feat_4_title', 'text', 'Tamper-Evident Packaging', 112],
        ['feat_4_text', 'text', 'Security-focused packaging and tamper-evident solutions designed to help protect pharmaceutical products.', 113],
        ['feat_4_image', 'image', 'assets/images/prod_tamper_labels.jpg', 114],
        ['feat_5_title', 'text', 'ColdSeal Blister Wallets', 115],
        ['feat_5_text', 'text', 'Secure, cold-seal packaging designed to protect pharmaceutical products with reliable sealing and easy handling.', 116],
        ['feat_5_image', 'image', 'assets/images/coldseal.jpg', 117],
        ['feat_6_title', 'text', 'Anti-Counterfeit Packaging', 118],
        ['feat_6_text', 'text', 'Security-focused packaging solutions designed to help protect pharmaceutical products from counterfeiting and tampering.', 119],
        ['feat_6_image', 'image', 'assets/images/engravix.jpg', 120],
        ['why_subtitle', 'text', 'WHY CHOOSE PRINCE ART PACKAGES', 121],
        ['why_title', 'text', 'Why Pharmaceutical Manufacturers Choose Prince Art Packages', 122],
        ['why_intro', 'text', 'Delivering audit-ready secondary packaging backed by decades of specialized manufacturing expertise, advanced multi-color offset printing, strict line clearance protocols, and end-to-end quality assurance.', 123],
        ['why_1_title', 'text', 'Pharmaceutical Packaging Expertise', 124],
        ['why_1_text', 'text', 'Specialized experience in pharmaceutical secondary packaging.', 125],
        ['why_2_title', 'text', 'Compliance-Focused Manufacturing', 126],
        ['why_2_text', 'text', 'Processes aligned with pharmaceutical quality and compliance requirements.', 127],
        ['why_3_title', 'text', 'Advanced Printing & Finishing', 128],
        ['why_3_text', 'text', 'High-quality printing and finishing capabilities for pharmaceutical packaging.', 129],
        ['why_4_title', 'text', 'Security & Anti-Counterfeit Solutions', 130],
        ['why_4_text', 'text', 'Packaging technologies designed to improve product security and brand protection.', 131],
        ['why_5_title', 'text', 'Quality Control', 132],
        ['why_5_text', 'text', 'Controlled quality processes throughout manufacturing.', 133],
        ['why_6_title', 'text', 'Customized Packaging', 134],
        ['why_6_text', 'text', 'Solutions developed according to customer packaging requirements.', 135],
        ['ind_sec_subtitle', 'text', 'INDUSTRIES WE SERVE', 136],
        ['ind_sec_title', 'text', 'Packaging Solutions for Regulated Industries', 137],
        ['ind_sec_intro', 'text', 'Specialized secondary packaging manufacturing tailored for regulated formulation plants.', 138],
        ['ind_1_title', 'text', 'Pharmaceutical', 139],
        ['ind_1_text', 'text', 'Prescription solid orals, liquids, parenterals, and cGMP regulated formulations.', 140],
        ['ind_1_pkg', 'text', 'Printed Cartons & Leaflets', 141],
        ['ind_2_title', 'text', 'Healthcare', 142],
        ['ind_2_text', 'text', 'Hospital supplies, diagnostic kits, and patient-care secondary packaging.', 143],
        ['ind_2_pkg', 'text', 'Barrier Cartons & Kit Boxes', 144],
        ['ind_3_title', 'text', 'Medical', 145],
        ['ind_3_text', 'text', 'Sterile surgical disposables, diagnostic reagents, and device packaging.', 146],
        ['ind_3_pkg', 'text', 'Cold-Chain Wallets & Inserts', 147],
        ['ind_4_title', 'text', 'Consumer Healthcare / OTC', 148],
        ['ind_4_text', 'text', 'OTC medicines, vitamins, supplements, and wellness formulations.', 149],
        ['ind_4_pkg', 'text', 'High-Gloss Boxes & Labels', 150],
        ['ind_5_title', 'text', 'Other Regulated Products', 151],
        ['ind_5_text', 'text', 'Cosmeceuticals, chemicals, and veterinary health products.', 152],
        ['ind_5_pkg', 'text', 'Tamper Seals & Serialized Cartons', 153],
        ['quality_sec_subtitle', 'text', 'QUALITY & COMPLIANCE', 154],
        ['quality_sec_title', 'text', 'Quality & Compliance at Every Stage', 155],
        ['quality_sec_intro', 'text', 'Verified international quality certifications, strict cGMP controls, and in-house laboratory testing ensuring audit-ready packaging.', 156],
        ['qual_cert_1_title', 'text', 'ISO 9001:2015', 157],
        ['qual_cert_1_sub', 'text', 'Certified QMS System', 158],
        ['qual_cert_2_title', 'text', 'cGMP Compliance', 159],
        ['qual_cert_2_sub', 'text', 'Line Clearance & Hygiene', 160],
        ['qual_cert_3_title', 'text', 'WHO-GMP Standards', 161],
        ['qual_cert_3_sub', 'text', 'Manufacturing Assurance', 162],
        ['qual_cert_4_title', 'text', 'FSC Chain of Custody', 163],
        ['qual_cert_4_sub', 'text', 'FSC-STD-40-004 Certified', 164],
        ['qual_pill_1_title', 'text', 'Quality Control', 165],
        ['qual_pill_1_text', 'text', 'In-house OurLAB testing: spectrophotometer color consistency, Pantone shade formulation, and ink-rub resistance.', 166],
        ['qual_pill_2_title', 'text', 'Manufacturing Controls', 167],
        ['qual_pill_2_text', 'text', 'Strict line clearance, air-controlled production floors, and dual-plant segregation to prevent artwork mix-ups.', 168],
        ['qual_pill_3_title', 'text', 'Inspection & Traceability', 169],
        ['qual_pill_3_text', 'text', 'Automated optical camera inspection, 2D serialization verification, and comprehensive batch retention archives.', 170],
        ['social_sec_subtitle', 'text', 'CLIENT TRUST & SOCIAL PROOF', 171],
        ['social_sec_title', 'text', 'Trusted by Pharmaceutical & Healthcare Companies', 172],
        ['social_sec_intro', 'text', 'Delivering audit-verified secondary packaging excellence, zero-defect delivery track records, and trusted partnerships across leading formulation plants.', 173],
        ['stat_1_val', 'text', '40+', 174],
        ['stat_1_lbl', 'text', 'Years of Heritage', 175],
        ['stat_2_val', 'text', '2 Plants', 176],
        ['stat_2_lbl', 'text', 'Korangi Creek, Karachi', 177],
        ['stat_3_val', 'text', '150M+', 178],
        ['stat_3_lbl', 'text', 'Annual Units Delivered', 179],
        ['stat_4_val', 'text', '99.98%', 180],
        ['stat_4_lbl', 'text', 'Zero-Defect Standard', 181],
        ['testi_1_quote', 'text', 'Prince Art Packages has consistently met our stringent QA line clearance standards. Their printed cartons run seamlessly on our high-speed cartoning lines with zero jamming.', 182],
        ['testi_1_name', 'text', 'Dr. Tariq Mahmood', 183],
        ['testi_1_desig', 'text', 'Head of Supply Chain & QA', 184],
        ['testi_1_company', 'text', 'Leading National Pharmaceutical Manufacturer', 185],
        ['testi_2_quote', 'text', 'Their miniature outsert leaflets and 27gsm inserts passed all automated barcode mix-up inspections. The dedication to compliance and delivery accuracy is unmatched.', 186],
        ['testi_2_name', 'text', 'Asif R. Siddiqui', 187],
        ['testi_2_desig', 'text', 'Director of Operations & Procurement', 188],
        ['testi_2_company', 'text', 'Healthcare & OTC Formulations Ltd.', 189],
        ['testi_3_quote', 'text', 'The dual-manufacturing setup in Korangi Creek gives our supply chain total peace of mind. Their technical team helped re-engineer our carton grain direction to eliminate waste.', 190],
        ['testi_3_name', 'text', 'Farhan A. Khan', 191],
        ['testi_3_desig', 'text', 'Production & Packaging Manager', 192],
        ['testi_3_company', 'text', 'Multinational Healthcare Group', 193],
        ['quote_sec_subtitle', 'text', 'QUICK RFQ & INQUIRY', 194],
        ['quote_sec_title', 'text', 'Request a Packaging Quote', 195],
        ['quote_sec_lead', 'text', 'Submit your pharmaceutical packaging requirements. Our technical sales and engineering team will evaluate your die-lines and provide an audit-ready commercial quotation within 24 business hours.', 196],
        ['quote_benefit_1_title', 'text', '24-Hour Quotation Turnaround', 197],
        ['quote_benefit_1_sub', 'text', 'Fast response with precise cost breakdowns and minimum order volumes.', 198],
        ['quote_benefit_2_title', 'text', 'cGMP & WHO-GMP Compliant', 199],
        ['quote_benefit_2_sub', 'text', 'Complete QA documentation, COA certificates, and plant audit support.', 200],
        ['quote_benefit_3_title', 'text', 'Die-lines & Physical Samples', 201],
        ['quote_benefit_3_sub', 'text', 'Sample packs, carton structural mock-ups, and folding outsert templates.', 202],
        ['quote_cta_label', 'text', 'Request My Quote', 203],
        ['faq_sec_subtitle', 'text', 'FREQUENTLY ASKED QUESTIONS', 204],
        ['faq_sec_title', 'text', 'Frequently Asked Questions', 195],
        ['faq_sec_intro', 'text', 'Essential answers regarding our pharmaceutical secondary packaging capabilities, compliance certifications, custom specifications, and ordering process.', 196],
        ['faq_1_q', 'text', 'What pharmaceutical packaging products does Prince Art Packages manufacture?', 197],
        ['faq_1_a', 'text', 'We manufacture specialized secondary packaging including paperboard printed cartons (reverse tuck, crash lock), ultra-thin 27gsm–60gsm patient prescribing information leaflets, miniature multi-folded outserts, self-adhesive roll labels, tamper-evident packaging, and ColdSeal blister wallets.', 198],
        ['faq_2_q', 'text', 'Does Prince Art Packages manufacture custom pharmaceutical cartons?', 199],
        ['faq_2_a', 'text', 'Yes. We engineer bespoke paperboard cartons customized to your product dimensions (blister packs, vials, bottles, ampoules) with custom grammage (230gsm–400gsm), high-precision die-cutting, embossing, Braille text, and specialty barrier finishes.', 200],
        ['faq_3_q', 'text', 'Are your manufacturing facilities cGMP compliant?', 201],
        ['faq_3_a', 'text', 'Yes. Both Unit 1 and Unit 2 in Korangi Creek Industrial Park operate under strict cGMP protocols, featuring segregated production lines, physical line clearance procedures, positive air pressure, and zero cross-contamination safeguards.', 202],
        ['faq_4_q', 'text', 'What certifications does Prince Art Packages have?', 203],
        ['faq_4_a', 'text', 'We hold ISO 9001:2015 Quality Management System Certification (Cert No: KQ.2025.5393) and FSC Chain of Custody Certification (FSC-C222205 / FSC-STD-40-004), fully aligned with WHO-GMP manufacturing and auditing standards.', 204],
        ['faq_5_q', 'text', 'Do you manufacture pharmaceutical leaflets and inserts?', 205],
        ['faq_5_a', 'text', 'Yes. We print ultra-thin 27gsm to 60gsm prescribing information inserts and miniature outserts on high-speed specialized folding equipment equipped with 100% electronic optical scanning to prevent line mix-ups.', 206],
        ['faq_6_q', 'text', 'Do you manufacture printed pharmaceutical labels?', 207],
        ['faq_6_a', 'text', 'Yes. We produce high-density self-adhesive roll labels for ampoules, vials, and bottles, printed on pharma-grade substrates with durable adhesives, 2D DataMatrix serialization, and scratch-resistant varnishes.', 208],
        ['faq_7_q', 'text', 'Do you provide tamper-evident packaging?', 209],
        ['faq_7_a', 'text', 'Yes. We engineer integrated tamper-evident cartons (perforated tear strips, locking security tucks) and destructible tamper-evident security labels that deliver immediate visual evidence of tampering.', 210],
        ['faq_8_q', 'text', 'Do you offer anti-counterfeit pharmaceutical packaging?', 211],
        ['faq_8_a', 'text', 'Yes. We offer proprietary optical security solutions including our 3D-Engravix™ security feature, covert micro-text, serialized 2D barcodes, guilloche patterns, and security inks to protect pharmaceutical brands from counterfeiting.', 212],
        ['faq_9_q', 'text', 'What information is required to request a quotation?', 213],
        ['faq_9_a', 'text', 'To receive an accurate quotation, please provide the packaging format (carton, leaflet, label), dimensions (L × W × H), paperboard/paper GSM, color specifications (CMYK/Pantone), special finishing requirements, and estimated order quantities.', 214],
        ['faq_10_q', 'text', 'Where is Prince Art Packages located?', 215],
        ['faq_10_a', 'text', 'Our corporate offices and two advanced production plants are located at WH-17-A8, ST-1, Sector 38 and Plot 239, Korangi Creek Industrial Park, Karachi, Pakistan.', 216],
        ['faq_11_q', 'text', 'Do you supply pharmaceutical packaging to international markets?', 217],
        ['faq_11_a', 'text', 'Yes. In addition to supplying leading pharmaceutical formulation plants across Pakistan, we export audit-compliant secondary packaging to regulated healthcare clients in international markets.', 218],
        ['banner_eyebrow', 'text', 'FEATURED INNOVATIONS', 225],
        ['banner_title', 'text', 'ColdSeal Blister Wallet & 3D-Engravix™ Security', 230],
        ['banner_text', 'text', 'Discover our proprietary anti-counterfeit optical security technology (3D-Engravix™) and pressure-sealed eco packaging (ColdSeal Blister Wallet) that reduces plastic/foil footprint by up to 50%.', 235],
        ['banner_image', 'image', 'assets/images/coldseal.jpg', 240],
    ],
    'about' => [
        ['page_eyebrow', 'text', 'Corporate History & Facilities', 10],
        ['page_title', 'text', 'Prince Art Packages (Private) Limited', 20],
        ['page_intro', 'text', 'Formerly Prince Art Press, our company has evolved into a premier ISO 9001:2015 and FSC certified manufacturer of pharmaceutical secondary packaging in Pakistan.', 30],
        ['section1_heading', 'text', 'Industrial Heritage & Dual Manufacturing Units', 40],
        ['section1_body', 'text', 'Prince Art Packages (Private) Limited operates two modern manufacturing units in Korangi Creek Industrial Park, Karachi. Our facilities are designed specifically to eliminate cross-contamination, artwork mix-ups, and batch discrepancies.', 50],
        ['locations_heading', 'text', 'Manufacturing Unit Locations:', 60],
        ['unit1_address', 'text', 'WH-17-A8, ST-1, Sector 38, Korangi Creek Industrial Park, Karachi, Pakistan.', 70],
        ['unit2_address', 'text', 'Plot 239, Opposite Masco, Main Korangi Creek Road, Karachi, Pakistan.', 80],
        ['facility_image', 'image', 'assets/images/facility.jpg', 90],
    ],
    'products' => [
        ['page_subtitle', 'text', 'Manufacturing Product Range', 10],
        ['page_title', 'text', 'Pharmaceutical Secondary Packaging Products', 20],
        ['page_intro', 'text', 'Purpose-engineered packaging solutions manufactured under ISO 9001:2015 and cGMP guidelines for regulated formulation plants.', 30],
        ['p1_tag', 'text', 'SECONDARY PACKAGING', 40],
        ['p1_title', 'text', 'Printed Cartons', 45],
        ['p1_desc', 'text', 'Precision-printed paperboard printed cartons engineered for automated high-speed packaging lines. Available in reverse tuck, crash lock, and custom dividers.', 50],
        ['p1_image', 'image', 'assets/images/prod_cartons.jpg', 55],
        ['p2_tag', 'text', 'PATIENT INFORMATION', 60],
        ['p2_title', 'text', 'Leaf-inserts', 65],
        ['p2_desc', 'text', 'Prescribing information leaflets (PIL) and patient instruction inserts folded to precise dimensions for automated cartoning line insertion.', 70],
        ['p2_image', 'image', 'assets/images/prod_leaflets.jpg', 75],
        ['p3_tag', 'text', 'CONTAINER LABELING', 80],
        ['p3_title', 'text', 'Printed Labels', 85],
        ['p3_desc', 'text', 'High-precision self-adhesive roll labels for pharmaceutical bottles, vials, ampoules, and IV containers with serialization barcode compatibility.', 90],
        ['p3_image', 'image', 'assets/images/prod_labels.jpg', 95],
        ['p4_tag', 'text', 'PROTECTIVE PARTITIONS', 100],
        ['p4_title', 'text', 'Honeycomb Separators', 105],
        ['p4_desc', 'text', 'Protective cardboard honeycomb dividers and grid partitions designed to safeguard glass ampoules and liquid vials against transit breakage.', 110],
        ['p4_image', 'image', 'assets/images/prod_honeycomb.jpg', 115],
        ['p5_tag', 'text', 'DOSE ADHERENCE', 120],
        ['p5_title', 'text', 'Pill-folders', 125],
        ['p5_desc', 'text', 'Paperboard medicine packaging wallets with integrated dose-tracking calendar compartments engineered to support patient medication adherence.', 130],
        ['p5_image', 'image', 'assets/images/prod_pill_folders.jpg', 135],
        ['p6_tag', 'text', 'SECURITY SEALS', 140],
        ['p6_title', 'text', 'Temper Evident Cartons & Labels', 145],
        ['p6_desc', 'text', 'Destructible security seals and tamper-evident carton structures that provide immediate, irreversible visual evidence if packaging has been breached.', 150],
        ['p6_image', 'image', 'assets/images/prod_tamper_labels.jpg', 155],
        ['p7_tag', 'text', 'OPTICAL ANTI-COUNTERFEIT', 160],
        ['p7_title', 'text', '3D-ENGRAVIX™', 165],
        ['p7_desc', 'text', 'Proprietary micro-structured optical security feature integrated directly onto printed cartons for instant visual authentication under ambient light.', 170],
        ['p7_image', 'image', 'assets/images/engravix.jpg', 175],
        ['p8_tag', 'text', 'PRESSURE-SEALED ECO PACKAGING', 180],
        ['p8_title', 'text', 'Cold-seal Wallet', 185],
        ['p8_desc', 'text', 'Pressure-sealed (non-heat-sealed) paperboard blister packaging wallet encapsulating blister cards without applying heat to temperature-sensitive medicine.', 190],
        ['p8_image', 'image', 'assets/images/coldseal.jpg', 195],
    ],
    'capabilities' => [
        ['hero_eyebrow', 'text', 'INDUSTRIAL MANUFACTURING INFRASTRUCTURE', 10],
        ['hero_title', 'text', 'Engineered for High-Volume Packaging. Built for Precision.', 20],
        ['hero_lead', 'text', 'Our integrated manufacturing infrastructure combines high-capacity offset printing, advanced coating, converting and finishing capabilities to deliver consistent pharmaceutical packaging at production scale.', 30],
        ['infra_eyebrow', 'text', 'PRODUCTION DEPARTMENTS', 40],
        ['infra_title', 'text', 'Manufacturing Infrastructure', 50],
        ['infra_desc', 'text', 'From printing and surface finishing to precision converting, our production infrastructure brings critical packaging processes together under one manufacturing operation.', 60],
        ['dept1_badge', 'text', '01 • PRINTING', 70],
        ['dept1_spec', 'text', '1–6 Color', 75],
        ['dept1_title', 'text', '15 Printing Machines', 80],
        ['dept1_desc', 'text', 'Sheetfed offset printing infrastructure supporting consistent, high-volume production across pharmaceutical packaging requirements.', 85],
        ['dept1_image', 'image', 'assets/images/prod_labels.jpg', 90],
        ['dept2_badge', 'text', '02 • SURFACE FINISHING', 95],
        ['dept2_spec', 'text', '3 Finishing Processes', 100],
        ['dept2_title', 'text', 'Coatings & Surface Finishing', 105],
        ['dept2_desc', 'text', 'Multiple coating processes provide flexibility across substrates, finishes and packaging requirements.', 110],
        ['dept2_image', 'image', 'assets/images/engravix.jpg', 115],
        ['dept3_badge', 'text', '03 • CONVERTING', 120],
        ['dept3_spec', 'text', '6 Units', 125],
        ['dept3_title', 'text', 'Die Cutting & Creasing', 130],
        ['dept3_desc', 'text', 'Dedicated die cutting and creasing capacity supporting accurate carton conversion and repeatable production output.', 135],
        ['dept3_image', 'image', 'assets/images/prod_cartons.jpg', 140],
        ['dept4_badge', 'text', '04 • CARTON ASSEMBLY', 145],
        ['dept4_spec', 'text', '2 Units', 150],
        ['dept4_title', 'text', 'Folding & Gluing', 155],
        ['dept4_desc', 'text', 'Folding and gluing capability designed for efficient carton conversion and dependable production continuity.', 160],
        ['dept4_image', 'image', 'assets/images/coldseal.jpg', 165],
        ['dept5_badge', 'text', '05 • LEAFLET PROCESSING', 170],
        ['dept5_spec', 'text', '4 Units', 175],
        ['dept5_title', 'text', 'Paper Folding', 180],
        ['dept5_desc', 'text', 'Dedicated paper folding capacity supporting pharmaceutical leaflets and folded printed materials.', 185],
        ['dept5_image', 'image', 'assets/images/prod_leaflets.jpg', 190],
        ['dept6_badge', 'text', '06 • STOCK PREPARATION', 195],
        ['dept6_spec', 'text', '8 Units', 200],
        ['dept6_title', 'text', 'Paper & Board Cutting', 205],
        ['dept6_desc', 'text', 'Precision cutting infrastructure supporting paper and board preparation throughout the production process.', 210],
        ['dept6_image', 'image', 'assets/images/prod_honeycomb.jpg', 215],
        ['scale_title', 'text', 'Built to Keep Production Moving.', 220],
        ['scale_desc', 'text', 'Integrated printing, coating, cutting, converting and finishing capabilities provide the production infrastructure required for high-volume pharmaceutical packaging.', 225],
        ['scale_cartons', 'text', '8–10 Million', 230],
        ['scale_leaflets', 'text', '23–25 Million', 235],
        ['cta_title', 'text', 'Planning Your Next Packaging Run?', 240],
        ['cta_desc', 'text', 'Share your packaging specification, expected volume and production timeline with our team.', 245],
    ],
    'innovation' => [
        ['page_subtitle', 'text', 'Proprietary Technology', 10],
        ['page_title', 'text', 'Advanced Packaging Innovations & Security Features', 20],
        ['page_intro', 'text', 'Protecting patient safety, brand integrity, and supply chain authenticity through cutting-edge packaging engineering.', 30],
        ['coldseal_badge', 'text', 'PATENT-PENDING ECO INNOVATION', 40],
        ['coldseal_title', 'text', 'ColdSeal Blister Wallet', 50],
        ['coldseal_desc', 'richtext', '<p>ColdSeal Blister Wallet is a pressure-sealed (non-heat-sealed) blister packaging system encapsulated between paperboard layers.</p><ul style="padding-left:1.25rem; color:var(--text-body); margin: 1rem 0;"><li><strong>50% Material Reduction:</strong> Reduces plastic and aluminum foil usage by up to 50% compared to traditional rigid blisters.</li><li><strong>Child-Resistant & Senior-Friendly:</strong> Engineered latch mechanisms compliant with safety standards.</li><li><strong>Dose Compliance Tracking:</strong> Integrated calendar layout for patient compliance adherence.</li><li><strong>Available Formats:</strong> Wallet format, Box format, and Card format.</li><li><strong>Applications:</strong> Tablets/capsules, pre-filled syringes/pens, ampoules/vials, droppers.</li></ul>', 60],
        ['coldseal_image', 'image', 'assets/images/coldseal.jpg', 70],
        ['engravix_badge', 'text', 'OPTICAL ANTI-COUNTERFEIT SECURITY', 80],
        ['engravix_title', 'text', '3D-Engravix™ Optical Technology', 90],
        ['engravix_desc', 'richtext', '<p>3D-Engravix™ is an advanced optical security feature integrated directly onto pharmaceutical printed cartons during manufacturing.</p><p><strong>Zero Equipment Needed:</strong> Authentication is 100% visual under ambient light. Pharmacists, distributors, healthcare professionals, and patients require NO scanner, smartphone app, or reader device.</p><h4 style="margin-top:1rem;">Authentication Principles:</h4><ol style="padding-left:1.25rem; color:var(--text-body); font-size:0.9rem;"><li><strong>Micro-Optic Motion:</strong> Spinning blade, flowing motion, and travelling light effects when tilted.</li><li><strong>Flip Effect:</strong> Seamless visual transformation between objects when package is tilted vertically.</li><li><strong>Seal-Base Color Shift:</strong> Angle-dependent color shift (e.g. violet-purple to emerald-green shift).</li></ol>', 100],
        ['engravix_image', 'image', 'assets/images/engravix.jpg', 110],
        ['suite_title', 'text', 'Security & Value Additions Suite', 120],
        ['suite_subtitle', 'text', 'In-house specialized security printing and finishing techniques', 130],
    ],
    'quality' => [
        ['page_subtitle', 'text', 'Regulatory Assurance', 10],
        ['page_title', 'text', 'Quality Certifications & In-House Testing Laboratory', 20],
        ['page_intro', 'text', 'Verified international quality management certifications and cGMP audit compliance documentation.', 30],
        ['iso_title', 'text', 'ISO 9001:2015 Certification', 40],
        ['iso_cert_no', 'text', 'KQ.2025.5393', 50],
        ['iso_body', 'text', 'ASCERT Certification and Training Services LLC', 60],
        ['iso_accreditation', 'text', 'MSCB-223', 70],
        ['iso_scope', 'text', 'Scope: Purchasing of paper materials, production and sales of pharmaceutical secondary packaging products.', 80],
        ['fsc_title', 'text', 'FSC Chain of Custody Certification', 90],
        ['fsc_cert_no', 'text', 'RR-COC-003348', 100],
        ['fsc_license', 'text', 'FSC-C222205', 110],
        ['fsc_validity', 'text', 'FSC-STD-40-004 (Validity: 19 Nov 2025 – 18 Nov 2030)', 120],
        ['fsc_scope', 'text', 'Scope: FSC 100%, FSC Mix, and FSC Recycled paper product manufacturing and supply.', 130],
        ['lab_title', 'text', 'Our Quality Control Laboratory (OurLAB)', 140],
        ['lab_desc', 'text', 'Our in-house laboratory is equipped with the latest pantone & spectrophotometer color controlling/measuring devices to develop exact color recipes, shades, ink-rub resistance testing, and moisture analysis according to client pharmaceutical requirements.', 150],
        ['banner_title', 'text', 'Have a Compliance or Audit Question?', 160],
        ['banner_desc', 'text', 'Our technical team can walk you through our full quality documentation on request.', 170],
    ],
    'industries' => [
        ['page_subtitle', 'text', 'Target Sectors', 10],
        ['page_title', 'text', 'Industries We Serve', 20],
        ['page_intro', 'text', 'Specialized secondary packaging manufacturing tailored for regulated formulation plants.', 30],
        ['ind1_title', 'text', 'Commercial Pharmaceuticals', 40],
        ['ind1_desc', 'text', 'Prescription solid orals, liquids, parenterals, and topical formulations requiring strict cGMP compliance.', 50],
        ['ind2_title', 'text', 'Healthcare & OTC Products', 60],
        ['ind2_desc', 'text', 'Consumer healthcare products, vitamin supplements, and over-the-counter medicine boxes.', 70],
        ['ind3_title', 'text', 'Biologics & Medical Devices', 80],
        ['ind3_desc', 'text', 'Cold-chain insulated partitions, sterile syringe packaging cards, and high-density labels.', 90],
        ['banner_title', 'text', "Don't See Your Industry Listed?", 100],
        ['banner_desc', 'text', 'We work with a wide range of regulated manufacturers — talk to us about your specific packaging needs.', 110],
    ],
    'case-studies' => [
        ['page_subtitle', 'text', 'Client Performance Metrics', 10],
        ['page_title', 'text', 'Case Studies & Manufacturing Results', 20],
        ['page_intro', 'text', 'Anonymized performance highlights illustrating our zero-defect delivery standards for pharmaceutical clients.', 30],
        ['cs1_tag', 'text', 'CASE STUDY #201', 40],
        ['cs1_title', 'text', '99.98% Defect-Free Delivery for Multinational Packaging Audit', 50],
        ['cs1_challenge', 'text', 'High-speed automated line jamming caused by carton creasing variation.', 60],
        ['cs1_solution', 'text', 'Re-engineered grain direction and score depth on 300 gsm FBB board.', 70],
        ['cs1_result', 'text', 'Zero carton line jams across 15M units delivered.', 80],
        ['cs2_tag', 'text', 'CASE STUDY #202', 90],
        ['cs2_title', 'text', 'Zero Mix-Up Outsert Leaflet Scanning System', 100],
        ['cs2_challenge', 'text', 'Mandate requiring 100% barcode verification on miniature outsert leaflets.', 110],
        ['cs2_solution', 'text', 'Integrated Pharma Code sensor scanning on miniature folding equipment.', 120],
        ['cs2_result', 'text', 'Passed 6 consecutive regulatory audits with zero mix-up findings.', 130],
    ],
    'blog' => [
        ['page_subtitle', 'text', 'PACKAGING INSIGHTS & TECHNICAL ARTICLES', 10],
        ['page_title', 'text', 'Pharmaceutical Packaging Insights', 20],
        ['page_intro', 'text', 'Technical publications, regulatory compliance guidelines, and anti-counterfeiting innovations from Prince Art Packages (Private) Limited.', 30],
    ],
    'contact' => [
        ['page_subtitle', 'text', 'Get in Touch', 10],
        ['intro_heading', 'text', 'Request a Quotation & Facility Visit', 20],
        ['intro_text', 'text', 'Contact our technical sales team or request a formal plant audit at Unit 1 or Unit 2 in Korangi Creek Industrial Park, Karachi.', 30],
        ['form_title', 'text', 'Request a Quotation', 40],
        ['form_subtitle', 'text', 'Fill out the form below to receive a formal technical quotation or schedule a plant audit.', 50],
        ['company_name', 'text', 'Prince Art Packages (Private) Limited', 60],
        ['company_subtitle', 'text', '(Formerly Prince Art Press)', 70],
        ['unit1_address', 'text', 'WH-17-A8, ST-1, Sector 38, Korangi Creek Industrial Park, Karachi, Pakistan.', 80],
        ['unit2_address', 'text', 'Plot 239, Opposite Masco, Main Korangi Creek Road, Karachi, Pakistan.', 90],
        ['phone_number', 'text', '+92 21-38893400-3', 100],
        ['email_address', 'text', 'info@princeartpackages.com', 110],
    ],
    'privacy' => [
        ['page_title', 'text', 'Privacy Policy', 10],
        ['page_body', 'richtext', '<p>Prince Art Packages (Private) Limited respects your privacy and is committed to protecting your personal information. This Privacy Policy outlines how we handle information collected through our website, quote requests, and client communications.</p><p>We collect basic business contact details (name, email, company, phone) submitted voluntarily through our quotation and inquiry forms. This information is strictly used for commercial communication, technical specification evaluations, and client order execution. We do not sell or lease your information to third parties.</p>', 20],
    ],
    'terms' => [
        ['page_title', 'text', 'Terms & Conditions', 10],
        ['page_body', 'richtext', '<p>Welcome to the official website of Prince Art Packages (Private) Limited. By accessing and using this website, you agree to comply with and be bound by the terms and conditions outlined herein.</p><p>All content, specifications, logos, and proprietary features (including 3D-Engravix™ and ColdSeal designs) are intellectual property of Prince Art Packages (Private) Limited. Unauthorized copying, reproduction, or redistribution is strictly prohibited.</p>', 20],
    ],
];

// Insert/Update all content blocks
$stmtGetPage = $pdo->prepare("SELECT id FROM pages WHERE slug = ? LIMIT 1");
$count = 0;
foreach ($allBlocks as $slug => $blocks) {
    $stmtGetPage->execute([$slug]);
    $pageRow = $stmtGetPage->fetch(PDO::FETCH_ASSOC);
    if (!$pageRow) {
        echo "Page '$slug' not found! Skipping...\n";
        continue;
    }
    $pageId = (int)$pageRow['id'];
    foreach ($blocks as [$key, $type, $content, $sort]) {
        $checkStmt = $pdo->prepare("SELECT content FROM content_blocks WHERE page_id = ? AND block_key = ?");
        $checkStmt->execute([$pageId, $key]);
        $existing = $checkStmt->fetch(PDO::FETCH_ASSOC);
        
        if ($existing) {
            if (trim($existing['content']) === '') {
                $upd = $pdo->prepare("UPDATE content_blocks SET content = ?, block_type = ?, sort_order = ? WHERE page_id = ? AND block_key = ?");
                $upd->execute([$content, $type, $sort, $pageId, $key]);
            }
        } else {
            $ins = $pdo->prepare("INSERT INTO content_blocks (page_id, block_key, block_type, content, sort_order) VALUES (?, ?, ?, ?, ?)");
            $ins->execute([$pageId, $key, $type, $content, $sort]);
        }
        $count++;
    }
}

echo "Successfully synchronized {$count} content blocks across all pages!\n";
