<?php
// includes/page_blocks_manifest.php â€” Central registry of default page content blocks
require_once __DIR__ . '/db.php';

function get_all_page_default_blocks(): array {
    return [
        'home' => [
            ['hero_title', 'text', 'Precision Pharmaceutical Secondary Packaging Engineered for Global Audit Compliance', 10],
            ['hero_subtitle', 'text', 'ISO 9001:2015 certified manufacturer of Printed Cartons, leaf-inserts, printed labels, ColdSeal blister wallets, and 3D-Engravixâ„¢ optical anti-counterfeit security packaging based in Korangi Creek Industrial Park, Karachi.', 20],
            ['hero_image', 'image', 'assets/images/engravix.jpg', 25],
            ['trust_1_title', 'text', 'ISO 9001:2015 Certified', 30],
            ['trust_1_text', 'text', 'Cert No. KQ.2025.5393 (ASCERT)', 35],
            ['trust_2_title', 'text', 'FSC Chain of Custody', 40],
            ['trust_2_text', 'text', 'Cert No. RR-COC-003348 (FSC-C222205)', 45],
            ['trust_3_title', 'text', 'cGMP Compliant', 50],
            ['trust_3_text', 'text', 'Strict Line Clearance & QA', 55],
            ['trust_5_title', 'text', 'WHO-GMP Compliant', 56],
            ['trust_5_text', 'text', 'Manufacturing Standards', 58],
            ['trust_4_title', 'text', 'Unit 1 & Unit 2 Plants', 60],
            ['trust_4_text', 'text', 'Korangi Creek Industrial Park', 65],
            ['values_subtitle', 'text', 'Supporting Value Points', 66],
            ['values_title', 'text', 'Engineered for Compliance & Pharmaceutical Precision', 67],
            ['values_intro', 'text', 'As a dedicated pharmaceutical secondary packaging partner, Prince Art Packages operates under strict cGMP and ISO 9001:2015 standards across two state-of-the-art facilities in Korangi Creek Industrial Park, Karachi. We deliver audited packaging integrity designed to meet rigorous global regulatory audits.', 68],
            ['value_1_title', 'text', 'Pharmaceutical Expertise', 69],
            ['value_1_text', 'text', 'Specialized secondary packaging solutions for pharmaceutical products.', 70],
            ['value_2_title', 'text', 'Compliance Focused', 71],
            ['value_2_text', 'text', 'Packaging manufactured with quality and regulatory requirements in mind.', 72],
            ['value_3_title', 'text', 'Precision Manufacturing', 73],
            ['value_3_text', 'text', 'Controlled production processes for consistent packaging quality.', 74],
            ['value_4_title', 'text', 'Custom Solutions', 75],
            ['value_4_text', 'text', 'Packaging engineered according to product and customer requirements.', 76],
            ['capability_subtitle', 'text', 'Manufacturing Capabilities', 80],
            ['capability_title', 'text', 'Comprehensive Pharmaceutical Packaging Solutions', 85],
            ['capability_intro', 'text', 'Purpose-engineered paperboard packaging, precision inserts, self-adhesive roll labels, and proprietary security features.', 90],
            ['feat_1_title', 'text', 'Printed Cartons', 85],
            ['feat_1_text', 'text', 'Reverse tuck, crash lock, tamper-evident, and child-resistant cartons printed on food & pharma-grade virgin board.', 90],
            ['feat_1_image', 'image', 'assets/images/prod_cartons.jpg', 91],
            ['feat_2_title', 'text', 'Leaf-Inserts', 95],
            ['feat_2_text', 'text', 'Ultra-thin 27gsm to 60gsm prescribing information inserts, cross-folded or miniature outserts for automated packaging lines.', 100],
            ['feat_2_image', 'image', 'assets/images/prod_leaflets.jpg', 101],
            ['feat_3_title', 'text', 'Printed Labels & Tamper-Evident', 105],
            ['feat_3_text', 'text', 'Self-adhesive roll labels for vials, bottles, ampoules, and destructible tamper-evident security seals with 2D barcode serialization.', 110],
            ['feat_3_image', 'image', 'assets/images/prod_labels.jpg', 111],
            ['feat_4_title', 'text', 'Tamper-Evident Packaging', 112],
            ['feat_4_text', 'text', 'Security-focused packaging and tamper-evident solutions designed to help protect pharmaceutical products.', 113],
            ['feat_4_image', 'image', 'assets/images/prod_tamper_labels.jpg', 114],
            ['feat_5_title', 'text', 'ColdSeal Blister Wallets', 115],
            ['feat_5_text', 'text', 'Secure, cold-seal packaging designed to protect pharmaceutical products with reliable sealing and easy handling.', 116],
            ['feat_5_image', 'image', 'assets/images/coldseal.jpg', 117],
            ['feat_6_title', 'text', 'Anti-Counterfeit Packaging', 118],
            ['feat_6_text', 'text', 'Security-focused packaging solutions designed to help protect pharmaceutical products from counterfeiting and tampering.', 119],
            ['feat_6_image', 'image', 'assets/images/engravix.jpg', 120],
            ['why_subtitle', 'text', 'WHY CHOOSE PRINCE ART PACKAGES', 121],
            ['why_title', 'text', 'Why Pharmaceutical Manufacturers Choose Prince Art Packages', 122],
            ['why_intro', 'text', 'Delivering audit-ready secondary packaging backed by decades of specialized manufacturing expertise, advanced multi-color offset printing, strict line clearance protocols, and end-to-end quality assurance.', 123],
            ['why_1_title', 'text', 'Pharmaceutical Packaging Expertise', 124],
            ['why_1_text', 'text', 'Specialized experience in pharmaceutical secondary packaging.', 125],
            ['why_2_title', 'text', 'Compliance-Focused Manufacturing', 126],
            ['why_2_text', 'text', 'Processes aligned with pharmaceutical quality and compliance requirements.', 127],
            ['why_3_title', 'text', 'Advanced Printing & Finishing', 128],
            ['why_3_text', 'text', 'High-quality printing and finishing capabilities for pharmaceutical packaging.', 129],
            ['why_4_title', 'text', 'Security & Anti-Counterfeit Solutions', 130],
            ['why_4_text', 'text', 'Packaging technologies designed to improve product security and brand protection.', 131],
            ['why_5_title', 'text', 'Quality Control', 132],
            ['why_5_text', 'text', 'Controlled quality processes throughout manufacturing.', 133],
            ['why_6_title', 'text', 'Customized Packaging', 134],
            ['why_6_text', 'text', 'Solutions developed according to customer packaging requirements.', 135],
            ['ind_sec_subtitle', 'text', 'INDUSTRIES WE SERVE', 136],
            ['ind_sec_title', 'text', 'Packaging Solutions for Regulated Industries', 137],
            ['ind_sec_intro', 'text', 'Specialized secondary packaging manufacturing tailored for regulated formulation plants.', 138],
            ['ind_1_title', 'text', 'Pharmaceutical', 139],
            ['ind_1_text', 'text', 'Prescription solid orals, liquids, parenterals, and cGMP regulated formulations.', 140],
            ['ind_1_pkg', 'text', 'Printed Cartons & Leaflets', 141],
            ['ind_2_title', 'text', 'Healthcare', 142],
            ['ind_2_text', 'text', 'Hospital supplies, diagnostic kits, and patient-care secondary packaging.', 143],
            ['ind_2_pkg', 'text', 'Barrier Cartons & Kit Boxes', 144],
            ['ind_3_title', 'text', 'Medical', 145],
            ['ind_3_text', 'text', 'Sterile surgical disposables, diagnostic reagents, and device packaging.', 146],
            ['ind_3_pkg', 'text', 'Cold-Chain Wallets & Inserts', 147],
            ['ind_4_title', 'text', 'Consumer Healthcare / OTC', 148],
            ['ind_4_text', 'text', 'OTC medicines, vitamins, supplements, and wellness formulations.', 149],
            ['ind_4_pkg', 'text', 'High-Gloss Boxes & Labels', 150],
            ['ind_5_title', 'text', 'Other Regulated Products', 151],
            ['ind_5_text', 'text', 'Cosmeceuticals, chemicals, and veterinary health products.', 152],
            ['ind_5_pkg', 'text', 'Tamper Seals & Serialized Cartons', 153],
            ['quality_sec_subtitle', 'text', 'QUALITY & COMPLIANCE', 154],
            ['quality_sec_title', 'text', 'Quality & Compliance at Every Stage', 155],
            ['quality_sec_intro', 'text', 'Verified international quality certifications, strict cGMP controls, and in-house laboratory testing ensuring audit-ready packaging.', 156],
            ['qual_cert_1_title', 'text', 'ISO 9001:2015', 157],
            ['qual_cert_1_sub', 'text', 'Certified QMS System', 158],
            ['qual_cert_2_title', 'text', 'cGMP Compliance', 159],
            ['qual_cert_2_sub', 'text', 'Line Clearance & Hygiene', 160],
            ['qual_cert_3_title', 'text', 'WHO-GMP Standards', 161],
            ['qual_cert_3_sub', 'text', 'Manufacturing Assurance', 162],
            ['qual_cert_4_title', 'text', 'FSC Chain of Custody', 163],
            ['qual_cert_4_sub', 'text', 'FSC-STD-40-004 Certified', 164],
            ['qual_pill_1_title', 'text', 'Quality Control', 165],
            ['qual_pill_1_text', 'text', 'In-house OurLAB testing: spectrophotometer color consistency, Pantone shade formulation, and ink-rub resistance.', 166],
            ['qual_pill_2_title', 'text', 'Manufacturing Controls', 167],
            ['qual_pill_2_text', 'text', 'Strict line clearance, air-controlled production floors, and dual-plant segregation to prevent artwork mix-ups.', 168],
            ['qual_pill_3_title', 'text', 'Inspection & Traceability', 169],
            ['qual_pill_3_text', 'text', 'Automated optical camera inspection, 2D serialization verification, and comprehensive batch retention archives.', 170],
            ['social_sec_subtitle', 'text', 'CLIENT TRUST & SOCIAL PROOF', 171],
            ['social_sec_title', 'text', 'Trusted by Pharmaceutical & Healthcare Companies', 172],
            ['social_sec_intro', 'text', 'Delivering audit-verified secondary packaging excellence, zero-defect delivery track records, and trusted partnerships across leading formulation plants.', 173],
            ['stat_1_val', 'text', '40+', 174],
            ['stat_1_lbl', 'text', 'Years of Heritage', 175],
            ['stat_2_val', 'text', '2 Plants', 176],
            ['stat_2_lbl', 'text', 'Korangi Creek, Karachi', 177],
            ['stat_3_val', 'text', '150M+', 178],
            ['stat_3_lbl', 'text', 'Annual Units Delivered', 179],
            ['stat_4_val', 'text', '99.98%', 180],
            ['stat_4_lbl', 'text', 'Zero-Defect Standard', 181],
            ['testi_1_quote', 'text', 'Prince Art Packages has consistently met our stringent QA line clearance standards. Their Printed Cartons run seamlessly on our high-speed cartoning lines with zero jamming.', 182],
            ['testi_1_name', 'text', 'Dr. Tariq Mahmood', 183],
            ['testi_1_desig', 'text', 'Head of Supply Chain & QA', 184],
            ['testi_1_company', 'text', 'Leading National Pharmaceutical Manufacturer', 185],
            ['testi_2_quote', 'text', 'Their miniature outsert leaflets and 27gsm inserts passed all automated barcode mix-up inspections. The dedication to compliance and delivery accuracy is unmatched.', 186],
            ['testi_2_name', 'text', 'Asif R. Siddiqui', 187],
            ['testi_2_desig', 'text', 'Director of Operations & Procurement', 188],
            ['testi_2_company', 'text', 'Multinational Healthcare Formulation Plant', 189],
        ],
        'about' => [
            ['page_eyebrow', 'text', 'Corporate History & Facilities', 10],
            ['page_title', 'text', 'Prince Art Packages (Private) Limited', 20],
            ['page_intro', 'text', 'Formerly Prince Art Press, our company has evolved into a premier ISO 9001:2015 and FSC certified manufacturer of pharmaceutical secondary packaging in Pakistan.', 30],
            ['intro_subtitle', 'text', 'Company Introduction', 40],
            ['intro_title', 'text', 'Who We Are', 50],
            ['intro_overview', 'richtext', 'Prince Art Packages is a pharmaceutical secondary packaging manufacturer focused on delivering reliable, precision-engineered <a href="products.php" class="text-link">pharmaceutical packaging solutions</a> for pharmaceutical and healthcare companies.', 60],
            ['intro_narrative', 'text', 'Operating two cGMP-aligned manufacturing plants in Korangi Creek Industrial Park, Karachi, we combine more than 40 years of industrial heritage with state-of-the-art multi-color offset printing, precision converting, and in-house laboratory quality controls to ensure zero-defect secondary packaging for regulated domestic and export healthcare markets.', 70],
            ['pillar_1_title', 'text', '40+ Years of Industry Experience', 80],
            ['pillar_1_desc', 'text', 'Originally founded over 40 years ago as Prince Art Press, our company has grown through four continuous decades of technical innovation into Prince Art Packages (Private) Limitedâ€”delivering unmatched consistency and industry trust.', 85],
            ['pillar_2_title', 'text', '100% Pharmaceutical Specialization', 90],
            ['pillar_2_desc', 'text', 'Our production facilities, machine lines, and quality control systems are dedicated exclusively to pharmaceutical secondary packaging, ensuring strict contamination control and compliance with health authority regulations.', 95],
            ['pillar_3_title', 'text', 'Dual Manufacturing Units', 100],
            ['pillar_3_desc', 'text', 'We operate two purpose-built manufacturing plants in Korangi Creek Industrial Park, Karachi (Unit 1 & Unit 2), providing supply chain redundancy and high-capacity production output.', 105],
            ['pillar_4_title', 'text', 'ISO 9001:2015 & FSC Certified', 110],
            ['pillar_4_desc', 'text', 'Our entire operations are certified under ISO 9001:2015 Quality Management Systems and FSC Chain of Custody (FSC-C222205 / FSC-STD-40-004), guaranteeing audited traceability.', 115],
            ['pillar_5_title', 'text', 'Modern Manufacturing Machinery', 120],
            ['pillar_5_desc', 'text', 'Equipped with multi-color sheetfed offset presses, precision automatic die-cutters, high-speed folder gluers with optical barcode sensors, and miniature paper folding machines.', 125],
            ['pillar_6_title', 'text', 'Strict Quality Controls & OurLAB', 130],
            ['pillar_6_desc', 'text', 'Our in-house quality control laboratory performs rigorous pre-press, on-press, and post-press testing including spectrophotometric delta-E color analysis, paper caliper verification, and ink rub resistance.', 135],
            ['pillar_7_title', 'text', 'Dedicated Technical Team', 140],
            ['pillar_7_desc', 'text', 'Staffed by experienced prepress designers, print production technologists, quality assurance auditors, and packaging engineers dedicated to meeting client specifications.', 145],
            ['pillar_8_title', 'text', 'Customer-Centric Partnership', 150],
            ['pillar_8_desc', 'text', 'We provide collaborative packaging design assistance, pilot batch sampling, rapid turnaround times, and flexible production scheduling to support our clients commercial launches.', 155],
            ['journey_subtitle', 'text', 'Company Journey & Experience', 100],
            ['journey_title', 'text', 'Built on Decades of Packaging Experience', 101],
            ['journey_paragraph', 'richtext', 'With more than three decades of specialized manufacturing heritage, Prince Art Packages has developed deep engineering mastery across Printed Cartons, prescribing leaflets, roll labels, and anti-counterfeit packaging. Our journey from foundational offset printing to advanced dual-plant <a href="capabilities.php" class="text-link">pharmaceutical packaging manufacturing capabilities</a> reflects an enduring commitment to regulatory precision, continuous technical reinvestment, and zero-defect packaging integrity for healthcare leaders across the region.', 102],
            ['trust_metric_val', 'text', '30+', 103],
            ['trust_metric_lbl', 'text', 'Years of Experience', 104],
            ['journey_stat_1_val', 'text', '500M+', 105],
            ['journey_stat_1_lbl', 'text', 'Secondary Packaging Units Produced Annually', 106],
            ['journey_stat_2_val', 'text', '100%', 107],
            ['journey_stat_2_lbl', 'text', 'Audit-Ready Line Clearance & Traceability', 108],
            ['journey_stat_3_val', 'text', '2 Plants', 109],
            ['journey_stat_3_lbl', 'text', 'Dual Production Facilities in Korangi Creek', 110],
            ['era_1_tag', 'text', 'ORIGINS', 111],
            ['era_1_title', 'text', 'Foundations as Prince Art Press', 112],
            ['era_1_desc', 'text', 'Established over 30 years ago, focusing on industrial printing excellence, paperboard conversion, and uncompromising ink formulation standards.', 113],
            ['era_2_tag', 'text', 'PHARMA PIVOT', 114],
            ['era_2_title', 'text', 'Pharmaceutical Specialization', 115],
            ['era_2_desc', 'text', 'Pivoted operations 100% towards regulated healthcare packaging, implementing cGMP segregation, line clearance protocols, and micro-folding technologies.', 116],
            ['era_3_tag', 'text', 'EXPANSION', 117],
            ['era_3_title', 'text', 'Dual Plant Infrastructure', 118],
            ['era_3_desc', 'text', 'Expanded into two specialized production units in Korangi Creek Industrial Park, Karachi, scaling multi-color offset lines and automated gluing machinery.', 119],
            ['era_4_tag', 'text', 'INNOVATION & AUDIT', 120],
            ['era_4_title', 'text', 'Global Accreditations & Security', 121],
            ['era_4_desc', 'text', 'Secured ISO 9001:2015 and FSC certifications; engineered proprietary ColdSeal blister wallets and 3D-Engravixâ„¢ optical anti-counterfeit cartons.', 122],
            ['qc_sec_subtitle', 'text', 'SECTION 07 â€” QUALITY & COMPLIANCE', 130],
            ['qc_sec_title', 'text', 'Quality and Compliance at the Core of Our Operations', 131],
            ['qc_sec_intro', 'richtext', 'Pharmaceutical packaging demands zero error tolerance. We place <a href="quality.php" class="text-link">quality and compliance</a> at the core of our operations, providing procurement leaders, QA managers, and regulatory auditors with absolute confidence through internationally verified certifications, strict cGMP line clearance, and in-house laboratory testing.', 132],
            ['qc_cgmp_title', 'text', 'cGMP Compliance', 133],
            ['qc_cgmp_desc', 'text', 'Strict line clearance protocols between production batches, air-controlled production bays, segregated raw material staging, and complete operator hygiene controls to eliminate cross-contamination and packaging mix-ups.', 134],
            ['qc_iso_title', 'text', 'ISO 9001:2015 Certification', 135],
            ['qc_iso_desc', 'text', 'Certified Quality Management System governing our entire manufacturing process from virgin paperboard procurement to precision offset printing, die-cutting, inspection, and customer delivery.', 136],
            ['qc_iso_no', 'text', 'KQ.2025.5393', 137],
            ['qc_iso_body', 'text', 'ASCERT Certification (MSCB-223)', 138],
            ['qc_fsc_title', 'text', 'FSC Chain of Custody', 139],
            ['qc_fsc_desc', 'text', 'FSC certified responsible raw material sourcing guaranteeing sustainable, traceable forest paperboard for regulated multinational pharmaceutical secondary packaging.', 140],
            ['qc_fsc_no', 'text', 'RR-COC-003348', 141],
            ['qc_fsc_lic', 'text', 'FSC-C222205 (Std: 40-004)', 142],
            ['qc_who_title', 'text', 'WHO-GMP Alignment', 143],
            ['qc_who_desc', 'text', 'Manufacturing practices strictly aligned with World Health Organization guidelines for pharmaceutical secondary packaging suppliers, ensuring audit compliance for export formulations.', 144],
            ['qc_lab_title', 'text', 'Quality Control Systems & In-House Testing Laboratory (OurLAB)', 145],
            ['qc_lab_desc', 'text', 'Our in-house QC laboratory tests every material batch prior to printing and post-converting using calibrated optical and mechanical instruments.', 146],
            ['diff_sec_subtitle', 'text', 'What Makes Us Different', 150],
            ['diff_sec_title', 'text', 'Why Choose Prince Art Packages', 151],
            ['diff_sec_intro', 'text', 'Delivering audit-ready secondary packaging engineered to prevent line stoppages, artwork mix-ups, and compliance vulnerabilities through focused manufacturing precision.', 152],
            ['usp_1_title', 'text', 'Pharmaceutical Focus', 153],
            ['usp_1_text', 'text', 'Specialized knowledge of pharmaceutical secondary packaging requirements.', 154],
            ['usp_2_title', 'text', 'Manufacturing Expertise', 155],
            ['usp_2_text', 'text', 'Integrated production capabilities for consistent output.', 156],
            ['usp_3_title', 'text', 'Quality Focus', 157],
            ['usp_3_text', 'text', 'Structured quality controls throughout production.', 158],
            ['usp_4_title', 'text', 'Compliance', 159],
            ['usp_4_text', 'text', 'Manufacturing processes designed around applicable pharmaceutical requirements.', 160],
            ['usp_5_title', 'text', 'Security & Innovation', 161],
            ['usp_5_text', 'richtext', 'Advanced <a href="innovation.php" class="text-link">anti-counterfeit packaging solutions</a> for product and brand protection.', 162],
            ['usp_6_title', 'text', 'Customer-Focused Solutions', 163],
            ['usp_6_text', 'text', 'Packaging developed around individual product and production requirements.', 164],
            ['faq_subtitle', 'text', 'Frequently Asked Questions', 170],
            ['faq_title', 'text', 'Frequently Asked Questions', 171],
            ['faq_intro', 'text', 'Explore clear answers to common buyer and compliance questions regarding our pharmaceutical secondary packaging manufacturing, cGMP facilities, certifications, and quotation process.', 172],
            ['faq_1_q', 'text', 'What does Prince Art Packages manufacture?', 173],
            ['faq_1_a', 'text', 'Prince Art Packages specializes exclusively in pharmaceutical secondary packaging. We manufacture precision-printed folding paperboard cartons, prescribing information leaflets (PIL), multi-folded outserts, self-adhesive roll labels, ColdSeal blister wallets, honeycomb partitions, and proprietary 3D-Engravixâ„¢ optical anti-counterfeit security packaging.', 174],
            ['faq_2_q', 'text', 'What is pharmaceutical secondary packaging?', 175],
            ['faq_2_a', 'text', 'Pharmaceutical secondary packaging refers to the exterior packaging componentsâ€”such as Printed Cartons, patient instruction leaflets, overwrap wallets, and container labelsâ€”that enclose, protect, and present the primary packaging (blisters, bottles, ampoules, vials). While primary packaging directly touches the medication, secondary packaging is vital for patient compliance, dosage tracking, light protection, tamper evidence, track-and-trace serialization, and meeting strict health authority labeling regulations.', 176],
            ['faq_3_q', 'text', 'How long has Prince Art Packages been in the packaging industry?', 177],
            ['faq_3_a', 'text', 'Prince Art Packages has been serving the packaging industry for more than 40 years. Founded originally as Prince Art Press, our company has built four decades of continuous manufacturing craftsmanship, evolving into a modernized, cGMP-compliant enterprise trusted by leading multinational and local pharmaceutical companies.', 178],
            ['faq_4_q', 'text', 'Where is Prince Art Packages located?', 179],
            ['faq_4_a', 'text', 'Our corporate headquarters and dual manufacturing facilities are strategically located in Karachi, Pakistan, within the prestigious Korangi Creek Industrial Park (KCIP). We operate two dedicated plants: Unit 1 at Sector 38 (KCIP) and Unit 2 on Main Korangi Creek Road, ensuring robust production redundancy and supply chain reliability.', 180],
            ['faq_5_q', 'text', 'What pharmaceutical packaging products do you manufacture?', 181],
            ['faq_5_a', 'text', 'Our core product lines include: (1) Paperboard Printed Cartons engineered for high-speed automated cartoning machines; (2) Prescribing Information Inserts & Outserts printed on 27gsm to 60gsm pharma-grade paper; (3) Self-Adhesive Container Labels with 2D DataMatrix barcode serialization; (4) ColdSeal Blister Wallets for heat-sensitive medicines; and (5) 3D-Engravixâ„¢ optical anti-counterfeit packaging.', 182],
            ['faq_6_q', 'text', 'Are your manufacturing facilities cGMP compliant?', 183],
            ['faq_6_a', 'text', 'Yes. Our production floors, line clearance procedures, and material handling workflows strictly adhere to Current Good Manufacturing Practice (cGMP) and WHO-GMP standards. We implement documented line clearances before and after every production run, positive air pressure zones, segregated staging areas, and full digital batch records to prevent cross-contamination and packaging mix-ups.', 184],
            ['faq_7_q', 'text', 'What certifications does Prince Art Packages have?', 185],
            ['faq_7_a', 'text', 'Prince Art Packages holds verified international accreditations including ISO 9001:2015 Quality Management System Certification (Certificate No. KQ.2025.5393 by ASCERT) and FSC Chain of Custody Certification (Certificate No. RR-COC-003348 / License Code FSC-C222205). Our facilities are fully audited and aligned with cGMP and WHO-GMP quality requirements.', 186],
            ['faq_8_q', 'text', 'Do you manufacture customized pharmaceutical packaging?', 187],
            ['faq_8_a', 'text', 'Yes, absolutely. We engineer customized secondary packaging tailored to client bottle, vial, blister, or medical device dimensions. Our in-house structural design team develops custom die-lines, security carton tucks, calendarized pill-folder formats, and bespoke protective partitions, supported by physical mock-ups and automated line testing prior to full-scale production.', 188],
            ['faq_9_q', 'text', 'Do you provide anti-counterfeit packaging solutions?', 189],
            ['faq_9_a', 'text', 'Yes. To safeguard pharmaceutical brands and patient health from counterfeit drugs, we provide proprietary 3D-Engravixâ„¢ micro-optical packaging features, tamper-evident destructive fiber tear seals, serialized 2D DataMatrix barcodes, guilloche security patterns, and specialized luminescent security inks that enable instant visual authentication.', 190],
            ['faq_10_q', 'text', 'How can I request a quotation?', 191],
            ['faq_10_a', 'richtext', 'You can easily <a href="contact.php" class="text-link">request a pharmaceutical packaging quote</a> by submitting our online RFQ form on the Contact page, emailing your technical specifications and dielines directly to info@princeartpackages.com, or calling our technical sales desk at +92 21-38893400-3. Our packaging engineers typically evaluate specifications and deliver a formal quotation within 24 hours.', 192],
        ],
        'products' => [
            ['hero_eyebrow', 'text', 'PHARMACEUTICAL SECONDARY PACKAGING CATALOG', 5],
            ['hero_title', 'text', 'Engineered Secondary Packaging Solutions for Regulated Pharma', 6],
            ['hero_intro', 'text', 'High-precision Printed Cartons, prescribing leaflets, self-adhesive roll labels, and protective partitions manufactured under ISO 9001:2015 and cGMP guidelines.', 7],
            ['sec_subtitle', 'text', 'MANUFACTURING PRODUCT RANGE', 10],
            ['sec_h2_title', 'text', 'Comprehensive Pharmaceutical Secondary Packaging Portfolio', 20],
            ['sec_h2_intro', 'text', 'Prince Art Packages manufactures a specialized range of secondary packaging tailored for pharmaceutical formulation plants, OTC healthcare brands, and medical device manufacturers. Every packaging format is precision-engineered for seamless operation on high-speed automated cartoning lines, blister sealers, and serialization barcode vision systems â€” ensuring zero defect rates, batch traceability, and full regulatory compliance.', 30],
            ['p1_tag', 'text', 'SECONDARY PACKAGING', 40],
            ['p1_title', 'text', 'Printed Cartons', 45],
            ['p1_desc', 'text', 'Precision-printed paperboard Printed Cartons engineered for automated high-speed packaging lines. Available in reverse tuck, crash lock, and custom dividers.', 50],
            ['p1_image', 'image', 'assets/images/prod_cartons.jpg', 55],
            ['p2_tag', 'text', 'PATIENT INFORMATION', 60],
            ['p2_title', 'text', 'Leaf-inserts', 65],
            ['p2_desc', 'text', 'Prescribing information leaflets (PIL) and patient instruction inserts folded to precise dimensions for automated cartoning line insertion.', 70],
            ['p2_image', 'image', 'assets/images/prod_leaflets.jpg', 75],
            ['p3_tag', 'text', 'CONTAINER LABELING', 80],
            ['p3_title', 'text', 'Printed Labels', 85],
            ['p3_desc', 'text', 'High-precision self-adhesive roll labels for pharmaceutical bottles, vials, ampoules, and IV containers with serialization barcode compatibility.', 90],
            ['p3_image', 'image', 'assets/images/prod_labels.jpg', 95],
            ['p4_tag', 'text', 'PROTECTIVE PARTITIONS', 100],
            ['p4_title', 'text', 'Honeycomb Separators', 105],
            ['p4_desc', 'text', 'Protective cardboard honeycomb dividers and grid partitions designed to safeguard glass ampoules and liquid vials against transit breakage.', 110],
            ['p4_image', 'image', 'assets/images/prod_honeycomb.jpg', 115],
            ['p5_tag', 'text', 'DOSE ADHERENCE', 120],
            ['p5_title', 'text', 'Pill-folders', 125],
            ['p5_desc', 'text', 'Paperboard medicine packaging wallets with integrated dose-tracking calendar compartments engineered to support patient medication adherence.', 130],
            ['p5_image', 'image', 'assets/images/prod_pill_folders.jpg', 135],
            ['p6_tag', 'text', 'SECURITY SEALS', 140],
            ['p6_title', 'text', 'Temper Evident Cartons & Labels', 145],
            ['p6_desc', 'text', 'Destructible security seals and tamper-evident carton structures that provide immediate, irreversible visual evidence if packaging has been breached.', 150],
            ['p6_image', 'image', 'assets/images/prod_tamper_labels.jpg', 155],
            ['p7_tag', 'text', 'OPTICAL ANTI-COUNTERFEIT', 160],
            ['p7_title', 'text', '3D-ENGRAVIXâ„¢', 165],
            ['p7_desc', 'text', 'Proprietary micro-structured optical security feature integrated directly onto Printed Cartons for instant visual authentication under ambient light.', 170],
            ['p7_image', 'image', 'assets/images/engravix.jpg', 175],
            ['p8_tag', 'text', 'PRESSURE-SEALED ECO PACKAGING', 180],
            ['p8_title', 'text', 'Cold-seal Wallet', 185],
            ['p8_desc', 'text', 'Pressure-sealed (non-heat-sealed) paperboard blister packaging wallet encapsulating blister cards without applying heat to temperature-sensitive medicine.', 190],
            ['p8_image', 'image', 'assets/images/coldseal.jpg', 195],
            ['faq_subtitle', 'text', 'Frequently Asked Questions', 200],
            ['faq_title', 'text', 'Product & Manufacturing FAQs', 205],
            ['faq_intro', 'text', 'Common technical questions regarding our pharmaceutical secondary packaging specifications, substrates, customization capabilities, machine compatibility, and minimum order requirements.', 210],
            ['faq_1_q', 'text', 'What pharmaceutical secondary packaging products does Prince Art Packages manufacture?', 220],
            ['faq_1_a', 'textarea', 'We manufacture a specialized range of regulated secondary packaging including high-precision Printed Cartons (RTE, STE, auto-lock crash bottom), Leaf-Inserts (prescribing leaflets and miniature outserts down to 27 GSM), self-adhesive Printed Labels, Honeycomb Separators for glass ampoules and vials, Dose-Adherence Pill-Folders, Tamper-Evident Cartons & Security Seals (EN 16679 compliant), 3D-ENGRAVIX™ Optical Anti-Counterfeit Cartons, and eco-friendly ColdSeal Blister Wallets.', 225],
            ['faq_2_q', 'text', 'Can you customize carton dimensions, dielines, and board calipers for our specific packaging machines?', 230],
            ['faq_2_a', 'textarea', 'Yes, absolutely. Our in-house structural design desk develops bespoke CAD dielines, electronic PDF proofs, and physical unprinted or printed sample mock-ups tailored to your exact primary container dimensions and automated cartoning lines (such as Bosch, Uhlmann, IMA, Marchesini, and Romaco).', 235],
            ['faq_3_q', 'text', 'What paperboard substrates and grammages are available for Printed Cartons?', 240],
            ['faq_3_a', 'textarea', 'We work with certified virgin Folding Box Board (FBB / GC1 and GC2), Solid Bleached Sulfate (SBS), and pharma-grade duplex boxboards ranging from 230 GSM to 450 GSM (thickness: 350 to 650 microns). All raw materials are sourced from FSC-certified and food/pharma-approved global mills.', 245],
            ['faq_4_q', 'text', 'How do you prevent product mix-ups on high-density Leaf-Inserts and miniature outserts?', 250],
            ['faq_4_a', 'textarea', 'Every leaflet folding line is equipped with 100% inline optical Pharma-Code and 2D barcode vision inspection scanners. Any unverified or mismatched leaflet is instantly rejected by high-speed pneumatic gates, ensuring zero mix-ups throughout production.', 255],
            ['faq_5_q', 'text', 'Are your packaging cartons and labels compatible with serialization (2D DataMatrix) requirements?', 260],
            ['faq_5_a', 'textarea', 'Yes. Our printed cartons and labels are formulated with high-contrast, non-smear aqueous top-coatings optimized for continuous inkjet (CIJ), thermal transfer (TTO), and inline laser serialization coding. Furthermore, our tamper-evident carton designs comply with EN 16679:2014 and EU Directive 2011/62/EU.', 265],
            ['faq_6_q', 'text', 'Do you provide in-line Braille embossing on pharmaceutical cartons?', 265],
            ['faq_6_a', 'textarea', 'Yes. We provide certified in-line Braille dot embossing conforming to the Marburg Medium standard (European Directive 2004/27/EC), with dot height and spacing verified via optical inspection gauges to guarantee legibility and disability compliance.', 270],
            ['faq_7_q', 'text', 'What are your standard production lead times and minimum order quantities (MOQ)?', 275],
            ['faq_7_a', 'textarea', 'Standard production lead times typically range from 7 to 14 business days after final artwork sign-off and batch clearance. We offer flexible MOQ tiers accommodating pilot formulation batches, clinical trial runs, and high-volume commercial production runs.', 280],
            ['faq_8_q', 'text', 'How can our QA or procurement team request physical samples or a formal technical quotation?', 285],
            ['faq_8_a', 'textarea', 'You can request physical sample kits, unprinted structural mock-ups, or a formal technical quotation directly through any product page on our website, or by contacting our Technical Sales Desk at +92 21-38893400-3 / sales@princeartpackages.com.', 290],
        ],
        'capabilities' => [
            ['hero_eyebrow', 'text', 'INDUSTRIAL MANUFACTURING INFRASTRUCTURE', 10],
            ['hero_title', 'text', 'Engineered for High-Volume Packaging. Built for Precision.', 20],
            ['hero_lead', 'text', 'Our integrated manufacturing infrastructure combines high-capacity offset printing, advanced coating, converting and finishing capabilities to deliver consistent pharmaceutical packaging at production scale.', 30],
            ['infra_eyebrow', 'text', 'PRODUCTION DEPARTMENTS', 40],
            ['infra_title', 'text', 'Manufacturing Infrastructure & Production Departments', 50],
            ['infra_desc', 'text', 'From printing and surface finishing to precision converting, our production infrastructure brings critical packaging processes together under one synchronized manufacturing operation.', 60],
            ['dept1_badge', 'text', '01 â€¢ PRINTING', 70],
            ['dept1_spec', 'text', '1â€“6 Color', 75],
            ['dept1_title', 'text', '15 Printing Machines', 80],
            ['dept1_desc', 'text', 'Sheetfed offset printing infrastructure supporting consistent, high-volume production across pharmaceutical packaging requirements.', 85],
            ['dept1_image', 'image', 'assets/images/prod_labels.jpg', 90],
            ['dept2_badge', 'text', '02 â€¢ SURFACE FINISHING', 95],
            ['dept2_spec', 'text', '3 Finishing Processes', 100],
            ['dept2_title', 'text', 'Coatings & Surface Finishing', 105],
            ['dept2_desc', 'text', 'Multiple coating processes provide flexibility across substrates, finishes and packaging requirements.', 110],
            ['dept2_image', 'image', 'assets/images/engravix.jpg', 115],
            ['dept3_badge', 'text', '03 â€¢ CONVERTING', 120],
            ['dept3_spec', 'text', '6 Units', 125],
            ['dept3_title', 'text', 'Die Cutting & Creasing', 130],
            ['dept3_desc', 'text', 'Dedicated die cutting and creasing capacity supporting accurate carton conversion and repeatable production output.', 135],
            ['dept3_image', 'image', 'assets/images/prod_cartons.jpg', 140],
            ['dept4_badge', 'text', '04 â€¢ CARTON ASSEMBLY', 145],
            ['dept4_spec', 'text', '2 Units', 150],
            ['dept4_title', 'text', 'Folding & Gluing', 155],
            ['dept4_desc', 'text', 'Folding and gluing capability designed for efficient carton conversion and dependable production continuity.', 160],
            ['dept4_image', 'image', 'assets/images/coldseal.jpg', 165],
            ['dept5_badge', 'text', '05 â€¢ LEAFLET PROCESSING', 170],
            ['dept5_spec', 'text', '4 Units', 175],
            ['dept5_title', 'text', 'Paper Folding', 180],
            ['dept5_desc', 'text', 'Dedicated paper folding capacity supporting pharmaceutical leaflets and folded printed materials.', 185],
            ['dept5_image', 'image', 'assets/images/prod_leaflets.jpg', 190],
            ['dept6_badge', 'text', '06 â€¢ STOCK PREPARATION', 195],
            ['dept6_spec', 'text', '8 Units', 200],
            ['dept6_title', 'text', 'Paper & Board Cutting', 205],
            ['dept6_desc', 'text', 'Precision cutting infrastructure supporting paper and board preparation throughout the production process.', 210],
            ['dept6_image', 'image', 'assets/images/prod_honeycomb.jpg', 215],
            ['scale_title', 'text', 'Built to Keep Production Moving.', 220],
            ['scale_desc', 'text', 'Integrated printing, coating, cutting, converting and finishing capabilities provide the production infrastructure required for high-volume pharmaceutical packaging.', 225],
            ['scale_cartons', 'text', '8â€“10 Million', 230],
            ['scale_leaflets', 'text', '23â€“25 Million', 235],
            ['cta_title', 'text', 'Planning Your Next Packaging Run?', 240],
            ['cta_desc', 'text', 'Share your packaging specification, expected volume and production timeline with our team.', 245],
        ],
        'innovation' => [
            ['hero_eyebrow', 'text', 'PROPRIETARY PACKAGING TECHNOLOGIES', 5],
            ['hero_title', 'text', 'Advanced Packaging Innovations & Anti-Counterfeiting Security', 6],
            ['hero_intro', 'text', 'Pioneering eco-friendly ColdSeal blister wallets and proprietary 3D-ENGRAVIXâ„¢ optical security structures for pharmaceutical patient safety and brand authentication.', 7],
            ['sec_subtitle', 'text', 'INNOVATION & BRAND PROTECTION', 10],
            ['sec_h2_title', 'text', 'Next-Generation Packaging Engineering for Patient Safety', 20],
            ['sec_h2_intro', 'text', 'As pharmaceutical markets face rising counterfeit threats and increasing environmental sustainability requirements, Prince Art Packages invests heavily in proprietary packaging engineering. From heat-free ColdSeal Blister Wallets that preserve temperature-sensitive pharmaceuticals while reducing plastic usage by up to 50%, to our patented 3D-ENGRAVIXâ„¢ micro-structured optical security cartons that provide instant ambient-light authentication without requiring electronic scanners, our innovations deliver robust supply chain integrity.', 30],
            ['coldseal_badge', 'text', 'PATENT-PENDING ECO INNOVATION', 40],
            ['coldseal_title', 'text', 'ColdSeal Blister Wallet', 50],
            ['coldseal_desc', 'richtext', '<p>ColdSeal Blister Wallet is a pressure-sealed (non-heat-sealed) blister packaging system encapsulated between paperboard layers.</p><ul style="padding-left:1.25rem; color:var(--text-body); margin: 1rem 0;"><li><strong>50% Material Reduction:</strong> Reduces plastic and aluminum foil usage by up to 50% compared to traditional rigid blisters.</li><li><strong>Child-Resistant & Senior-Friendly:</strong> Engineered latch mechanisms compliant with safety standards.</li><li><strong>Dose Compliance Tracking:</strong> Integrated calendar layout for patient compliance adherence.</li><li><strong>Available Formats:</strong> Wallet format, Box format, and Card format.</li><li><strong>Applications:</strong> Tablets/capsules, pre-filled syringes/pens, ampoules/vials, droppers.</li></ul>', 60],
            ['coldseal_image', 'image', 'assets/images/coldseal.jpg', 70],
            ['engravix_badge', 'text', 'OPTICAL ANTI-COUNTERFEIT SECURITY', 80],
            ['engravix_title', 'text', '3D-Engravixâ„¢ Optical Technology', 90],
            ['engravix_desc', 'richtext', '<p>3D-Engravixâ„¢ is an advanced optical security feature integrated directly onto pharmaceutical Printed Cartons during manufacturing.</p><p><strong>Zero Equipment Needed:</strong> Authentication is 100% visual under ambient light. Pharmacists, distributors, healthcare professionals, and patients require NO scanner, smartphone app, or reader device.</p><h4 style="margin-top:1rem;">Authentication Principles:</h4><ol style="padding-left:1.25rem; color:var(--text-body); font-size:0.9rem;"><li><strong>Micro-Optic Motion:</strong> Spinning blade, flowing motion, and travelling light effects when tilted.</li><li><strong>Flip Effect:</strong> Seamless visual transformation between objects when package is tilted vertically.</li><li><strong>Seal-Base Color Shift:</strong> Angle-dependent color shift (e.g. violet-purple to emerald-green shift).</li></ol>', 100],
            ['engravix_image', 'image', 'assets/images/engravix.jpg', 110],
            ['suite_title', 'text', 'Security & Value Additions Suite', 120],
            ['suite_subtitle', 'text', 'In-house specialized security printing and finishing techniques', 130],
        ],
        'quality' => [
            ['hero_eyebrow', 'text', 'REGULATORY ASSURANCE & AUDIT COMPLIANCE', 5],
            ['hero_title', 'text', 'Quality & Compliance at the Core of Our Operations', 10],
            ['hero_intro', 'text', 'Stringent cGMP protocols, ISO 9001:2015 certification, and FSC Chain of Custody standards ensuring zero-defect packaging for regulated healthcare markets.', 15],
            
            ['commit_subtitle', 'text', 'PHARMACEUTICAL QUALITY COMMITMENT', 20],
            ['commit_title', 'text', 'Uncompromising Quality Standards for Patient Safety', 25],
            ['commit_intro', 'text', 'In pharmaceutical secondary packaging, quality is not merely an inspection checkpoint—it is the foundational pillar of patient safety and brand protection. Prince Art Packages operates under a total quality management philosophy where every printed carton, prescribing leaflet, and security label is engineered to prevent line stoppages, eliminate artwork mix-ups, and withstand rigorous regulatory audits.', 30],
            ['commit_pillar_1_title', 'text', 'Zero Error Tolerance', 35],
            ['commit_pillar_1_desc', 'text', 'Rigorous SOPs and continuous line monitoring ensure zero deviation from approved technical specifications.', 40],
            ['commit_pillar_2_title', 'text', '100% Batch Traceability', 45],
            ['commit_pillar_2_desc', 'text', 'Full end-to-end documentation from incoming raw paperboard reels to finished carton dispatch with assigned batch codes.', 50],
            ['commit_pillar_3_title', 'text', 'Independent QA Oversight', 55],
            ['commit_pillar_3_desc', 'text', 'Our Quality Assurance department operates with full autonomous stop-production authority across both manufacturing plants.', 60],
            ['commit_pillar_4_title', 'text', 'Continuous Reinvestment', 65],
            ['commit_pillar_4_desc', 'text', 'Ongoing capital investments in calibrated optical testing instruments, inline sensor inspection, and automated tooling.', 70],

            ['cert_hub_subtitle', 'text', 'GLOBAL ACCREDITATIONS', 75],
            ['cert_hub_title', 'text', 'Internationally Verified Certifications & Standards', 80],
            ['cert_hub_intro', 'text', 'Our dual manufacturing facilities in Korangi Creek Industrial Park, Karachi, operate in full compliance with internationally recognized quality and environmental stewardship frameworks.', 85],

            ['cgmp_subtitle', 'text', 'MANUFACTURING DISCIPLINE', 90],
            ['cgmp_title', 'text', 'cGMP Compliance & Zero-Mixup Packaging Controls', 95],
            ['cgmp_intro', 'text', 'Current Good Manufacturing Practices (cGMP) govern every step of our printing, folding, gluing, and converting workflows. Designed specifically for pharmaceutical clients, our facility protocols eliminate cross-contamination and ensure audit-ready consistency.', 100],
            ['cgmp_1_title', 'text', 'Formal Line Clearance Protocols', 105],
            ['cgmp_1_desc', 'text', 'Documented multi-point physical and digital line clearance before and after every production run to ensure no leftover material from previous batches.', 110],
            ['cgmp_2_title', 'text', '100% Optical Barcode & Pharma-Code Verification', 115],
            ['cgmp_2_desc', 'text', 'High-speed sensor cameras on folder-gluers and leaflet folding lines verify 100% of 2D DataMatrix and miniature barcodes with automated pneumatic rejection.', 120],
            ['cgmp_3_title', 'text', 'Controlled Environmental Conditions', 125],
            ['cgmp_3_desc', 'text', 'Temperature and humidity-regulated converting halls protect paperboard dimensional stability and prevent moisture warping.', 130],
            ['cgmp_4_title', 'text', 'Complete Batch Production Records (BPR)', 135],
            ['cgmp_4_desc', 'text', 'Every batch is accompanied by comprehensive Batch Manufacturing Records (BMR) detailing operators, machine parameters, ink lot numbers, and QC signatures.', 140],

            ['iso_title', 'text', 'ISO 9001:2015 Quality Management System', 145],
            ['iso_cert_no', 'text', 'KQ.2025.5393', 150],
            ['iso_body', 'text', 'ASCERT Certification and Training Services LLC', 155],
            ['iso_accreditation', 'text', 'MSCB-223', 160],
            ['iso_scope', 'text', 'Scope: Purchasing of paper materials, production and sales of pharmaceutical secondary packaging products.', 165],
            ['iso_desc', 'text', 'Our certified Quality Management System enforces structured risk assessment, calibrated measurement tracking, supplier audits, and systematic root-cause corrective actions (CAPA).', 170],

            ['fsc_title', 'text', 'FSC Chain of Custody Certification', 175],
            ['fsc_cert_no', 'text', 'RR-COC-003348', 180],
            ['fsc_license', 'text', 'FSC-C222205', 185],
            ['fsc_validity', 'text', 'FSC-STD-40-004 (Validity: 19 Nov 2025 – 18 Nov 2030)', 190],
            ['fsc_scope', 'text', 'Scope: FSC 100%, FSC Mix, and FSC Recycled paper product manufacturing and supply.', 195],
            ['fsc_desc', 'text', 'Guarantees that all virgin boxboards and lightweight leaflet papers are sourced from responsibly managed forests adhering to strict environmental, social, and economic sustainability standards.', 200],

            ['mat_subtitle', 'text', 'RAW MATERIAL QUALITY ASSURANCE', 205],
            ['mat_title', 'text', 'Incoming Material Inspection & Laboratory Testing (OurLAB)', 210],
            ['mat_intro', 'text', 'Zero-defect packaging starts with flawless raw materials. Every incoming shipment of paperboard, inks, varnishes, foils, and adhesives undergoes rigorous quarantine and laboratory verification prior to release into production.', 215],
            ['mat_1_title', 'text', 'GSM & Caliper Micrometer Verification', 220],
            ['mat_1_desc', 'text', 'Digital micrometer gauges and precision analytical balances verify paperboard thickness (microns) and substance (GSM) within ±2% tolerances.', 225],
            ['mat_2_title', 'text', 'Moisture Content & Cobb Sizing Analysis', 230],
            ['mat_2_desc', 'text', 'Electronic moisture analyzers and Cobb sizing testers measure board water absorption capacity to prevent carton curling and delamination.', 235],
            ['mat_3_title', 'text', 'Spectrophotometric Ink & Delta-E Tolerance', 240],
            ['mat_3_desc', 'text', 'Low-migration vegetable oil-based inks are calibrated with digital spectrophotometers to maintain Delta-E color variance under 1.5 across production.', 245],
            ['mat_4_title', 'text', 'Adhesive Tack, Viscosity & Fiber-Tear Testing', 250],
            ['mat_4_desc', 'text', 'Medical-grade adhesives and hot-melts are tested for bonding strength and guaranteed fiber tear under ambient, refrigerated, and deep-freeze temperatures.', 255],

            ['faq_subtitle', 'text', 'Frequently Asked Questions', 260],
            ['faq_title', 'text', 'Quality, Compliance & Audit FAQs', 265],
            ['faq_intro', 'text', 'Explore detailed answers regarding our pharmaceutical packaging audit procedures, Certificate of Analysis (CoA) dispatch, line clearance verification, and laboratory testing protocols.', 270],
            ['faq_1_q', 'text', 'Can our Quality Assurance and Regulatory team conduct an on-site facility audit?', 275],
            ['faq_1_a', 'textarea', 'Yes, absolutely. We regularly host scheduled facility audits for multinational pharmaceutical manufacturers, regulatory authorities, and independent inspection bodies. We provide full access to our SOPs, equipment validation documentation, calibration logs, and cGMP production floors in Korangi Creek, Karachi.', 280],
            ['faq_2_q', 'text', 'Do you provide a Certificate of Analysis (CoA) with every delivered batch?', 285],
            ['faq_2_a', 'textarea', 'Yes. Every dispatched shipment is accompanied by a formal Certificate of Analysis (CoA) and Certificate of Conformance (CoC) signed by our QA Manager, detailing substrate GSM, caliper, moisture levels, ink batch numbers, barcode scan grades, and line clearance verification.', 290],
            ['faq_3_q', 'text', 'How is line clearance managed between different customer packaging runs?', 295],
            ['faq_3_a', 'textarea', 'We enforce strict 3-tier cGMP line clearance SOPs. Before any new job begins, the previous job materials, plates, cutting dies, waste, and documentation are completely cleared from the packaging cell. Line clearance is physically inspected and dual-signed by the Line Incharge and the QA Inspector before machine startup.', 300],
            ['faq_4_q', 'text', 'What spectrophotometric color tolerances (Delta-E) do you guarantee?', 305],
            ['faq_4_a', 'textarea', 'Our offset presses operate with closed-loop inline spectrophotometry and densitometry calibrated to X-Rite Pantone digital color standards. We maintain Delta-E (ΔE) color variances under 1.5 to guarantee exact brand shade consistency across multiple batches over years of production.', 310],
            ['faq_5_q', 'text', 'How is Braille embossing verified on pharmaceutical cartons?', 315],
            ['faq_5_a', 'textarea', 'Braille embossing is applied in-line using precision CNC tooling compliant with the Marburg Medium standard (European Directive 2004/27/EC). Our QA laboratory verifies dot height (0.20 mm standard) and dot spacing across sampling sheets using calibrated optical depth micrometers.', 320],
            ['faq_6_q', 'text', 'What is your procedure for Corrective and Preventive Actions (CAPA)?', 325],
            ['faq_6_a', 'textarea', 'Under our ISO 9001:2015 QMS framework, any identified non-conformance initiates a structured CAPA investigation utilizing 5-Why root-cause analysis and Ishikawa fishbone diagrams. Corrective actions are implemented, documented, and audited for long-term effectiveness within 14 business days.', 330],

            ['cta_title', 'text', 'Schedule a Facility Audit or Request Quality Manual', 335],
            ['cta_desc', 'text', 'Speak directly with our Quality Assurance Directorate to arrange an on-site audit, request technical compliance dossiers, or review our laboratory testing capabilities.', 340],
        ],
        'industries' => [
            ['hero_eyebrow', 'text', 'TARGET PHARMACEUTICAL SECTORS', 5],
            ['hero_title', 'text', 'Specialized Packaging Solutions for Regulated Healthcare Industries', 6],
            ['hero_intro', 'text', 'Tailored secondary packaging engineered specifically for commercial pharmaceuticals, consumer healthcare & OTC products, and sterile biologics & medical devices.', 7],
            ['sec_subtitle', 'text', 'TARGET SECTORS & FORMULATION TYPES', 10],
            ['sec_h2_title', 'text', 'Purpose-Built Packaging for Diverse Healthcare Demands', 20],
            ['sec_h2_intro', 'text', 'Every healthcare sector possesses distinct regulatory standards, shelf-life conditions, and machine packing requirements. Prince Art Packages provides purpose-engineered paperboard packaging, patient information leaflets, and security labels adapted to the specific operational constraints of pharmaceutical tablet/capsule blister packing, liquid syrup bottling, ampoule/vial cartoning, and cold-chain biologics storage.', 30],
            ['ind1_title', 'text', 'Commercial Pharmaceuticals', 40],
            ['ind1_desc', 'text', 'Prescription solid orals, liquids, parenterals, and topical formulations requiring strict cGMP compliance.', 50],
            ['ind2_title', 'text', 'Healthcare & OTC Products', 60],
            ['ind2_desc', 'text', 'Consumer healthcare products, vitamin supplements, and over-the-counter medicine boxes.', 70],
            ['ind3_title', 'text', 'Biologics & Medical Devices', 80],
            ['ind3_desc', 'text', 'Cold-chain insulated partitions, sterile syringe packaging cards, and high-density labels.', 90],
            ['banner_title', 'text', "Don't See Your Industry Listed?", 100],
            ['banner_desc', 'text', 'We work with a wide range of regulated manufacturers â€” talk to us about your specific packaging needs.', 110],
        ],
        'case-studies' => [
            ['hero_eyebrow', 'text', 'PROVEN MANUFACTURING RESULTS', 5],
            ['hero_title', 'text', 'Proven Manufacturing Results & Audit Performance Metrics', 6],
            ['hero_intro', 'text', 'Discover how our precision packaging engineering delivers 99.98% defect-free output, zero cartoning line jams, and 100% regulatory audit compliance.', 7],
            ['sec_subtitle', 'text', 'AUDIT PERFORMANCE & CLIENT METRICS', 10],
            ['sec_h2_title', 'text', 'Real-World Engineering Solutions & Zero-Defect Delivery', 20],
            ['sec_h2_intro', 'text', 'Modern pharmaceutical packaging requires strict adherence to technical tolerances and rigorous cGMP line clearance. Explore how Prince Art Packages collaborates with leading pharmaceutical manufacturers to solve high-speed cartoning line jams, eliminate leaflet mix-ups with automated sensor vision systems, and pass comprehensive multinational quality audits.', 30],
            ['cs1_tag', 'text', 'CASE STUDY #201', 40],
            ['cs1_title', 'text', '99.98% Defect-Free Delivery for Multinational Packaging Audit', 50],
            ['cs1_challenge', 'text', 'High-speed automated line jamming caused by carton creasing variation.', 60],
            ['cs1_solution', 'text', 'Re-engineered grain direction and score depth on 300 gsm FBB board.', 70],
            ['cs1_result', 'text', 'Zero carton line jams across 15M units delivered.', 80],
            ['cs2_tag', 'text', 'CASE STUDY #202', 90],
            ['cs2_title', 'text', 'Zero Mix-Up Outsert Leaflet Scanning System', 100],
            ['cs2_challenge', 'text', 'Mandate requiring 100% barcode verification on miniature outsert leaflets.', 110],
            ['cs2_solution', 'text', 'Integrated Pharma Code sensor scanning on miniature folding equipment.', 120],
            ['cs2_result', 'text', 'Passed 6 consecutive regulatory audits with zero mix-up findings.', 130],
        ],
        'blog' => [
            ['hero_eyebrow', 'text', 'TECHNICAL INSIGHTS & REGULATORY UPDATES', 5],
            ['hero_title', 'text', 'Pharmaceutical Packaging Insights & Technical Knowledge', 6],
            ['hero_intro', 'text', 'Expert analysis, compliance guides, material selection insights, and engineering updates from Prince Art Packages technical desk.', 7],
            ['sec_subtitle', 'text', 'KNOWLEDGE & INDUSTRY ARTICLES', 10],
            ['sec_h2_title', 'text', 'Latest Technical Articles & Industry Guidelines', 20],
            ['sec_h2_intro', 'text', 'Stay informed on regulatory changes, pharmaceutical secondary packaging best practices, anti-counterfeit advancements, and sustainable packaging materials. Authored by our packaging engineers and quality assurance specialists, our publications provide practical technical insights for pharmaceutical production managers, regulatory affairs leads, and procurement teams.', 30],
        ],
        'contact' => [
            ['hero_subtitle', 'text', 'Company Introduction', 5],
            ['hero_title', 'text', 'Contact Prince Art Packages', 6],
            ['hero_copy', 'text', 'Have a question about our pharmaceutical packaging products, manufacturing capabilities or packaging solutions? Get in touch with our team.', 7],
            ['page_subtitle', 'text', 'Get in Touch', 10],
            ['intro_heading', 'text', 'Request a Quotation & Facility Visit', 20],
            ['intro_text', 'text', 'Contact our technical sales team or request a formal plant audit at Unit 1 or Unit 2 in Korangi Creek Industrial Park, Karachi.', 30],
            ['form_title', 'text', 'Request a Quotation', 40],
            ['form_subtitle', 'text', 'Fill out the form below to receive a formal technical quotation or schedule a plant audit.', 50],
            ['company_name', 'text', 'Prince Art Packages (Private) Limited', 60],
            ['company_subtitle', 'text', '(Formerly Prince Art Press)', 70],
            ['unit1_address', 'text', 'WH-17-A8, ST-1, Sector 38, Korangi Creek Industrial Park, Karachi, Pakistan.', 80],
            ['unit2_address', 'text', 'Plot 239, Opposite Masco, Main Korangi Creek Road, Karachi, Pakistan.', 90],
            ['phone_number', 'text', '+92 21-38893400-3', 100],
            ['email_address', 'text', 'info@princeartpackages.com', 110],
            ['business_hours', 'text', 'Monday â€“ Saturday: 9:00 AM â€“ 5:00 PM', 115],
            ['map_sec_subtitle', 'text', 'SECTION 07 â€” GOOGLE MAP', 120],
            ['map_sec_title', 'text', 'Our Location', 121],
            ['map_sec_intro', 'text', 'Visit our dual pharmaceutical secondary packaging manufacturing facilities in Korangi Creek Industrial Park, Karachi. We welcome prospective clients, technical auditors, and procurement teams for scheduled facility audits.', 122],
            ['map_embed_url', 'text', 'https://maps.google.com/maps?q=Korangi+Creek+Industrial+Park,+Karachi,+Pakistan&t=&z=15&ie=UTF8&iwloc=&output=embed', 123],
        ],
        'privacy' => [
            ['page_title', 'text', 'Privacy Policy', 10],
            ['page_body', 'richtext', '<p>Prince Art Packages (Private) Limited respects your privacy and is committed to protecting your personal information. This Privacy Policy outlines how we handle information collected through our website, quote requests, and client communications.</p><p>We collect basic business contact details (name, email, company, phone) submitted voluntarily through our quotation and inquiry forms. This information is strictly used for commercial communication, technical specification evaluations, and client order execution. We do not sell or lease your information to third parties.</p>', 20],
        ],
        'terms' => [
            ['page_title', 'text', 'Terms & Conditions', 10],
            ['page_body', 'richtext', '<p>Welcome to the official website of Prince Art Packages (Private) Limited. By accessing and using this website, you agree to comply with and be bound by the terms and conditions outlined herein.</p><p>All content, specifications, logos, and proprietary features (including 3D-Engravixâ„¢ and ColdSeal designs) are intellectual property of Prince Art Packages (Private) Limited. Unauthorized copying, reproduction, or redistribution is strictly prohibited.</p>', 20],
        ],
    ];
}

function ensure_page_default_blocks(PDO $pdo, string $pageSlug): void {
    $all = get_all_page_default_blocks();
    if (!isset($all[$pageSlug])) return;
    
    $stmt = $pdo->prepare("SELECT id FROM pages WHERE slug = ? LIMIT 1");
    $stmt->execute([$pageSlug]);
    $page = $stmt->fetch(PDO::FETCH_ASSOC);
    if (!$page) return;
    $pageId = (int)$page['id'];
    
    $checkStmt = $pdo->prepare("SELECT id FROM content_blocks WHERE page_id = ? AND block_key = ? LIMIT 1");
    $insStmt = $pdo->prepare("INSERT INTO content_blocks (page_id, block_key, block_type, content, sort_order) VALUES (?, ?, ?, ?, ?)");
    
    // Auto-migrate legacy trust_3_text if it still holds previous WHO-GMP text
    if ($pageSlug === 'home') {
        $pdo->prepare("UPDATE content_blocks SET content = 'Strict Line Clearance & QA' WHERE page_id = ? AND block_key = 'trust_3_text' AND content = 'WHO-GMP Manufacturing Standards'")->execute([$pageId]);
    }

    foreach ($all[$pageSlug] as [$key, $type, $content, $sort]) {
        $checkStmt->execute([$pageId, $key]);
        if (!$checkStmt->fetch()) {
            $insStmt->execute([$pageId, $key, $type, $content, $sort]);
        }
    }
}

function restore_page_default_blocks(PDO $pdo, string $pageSlug): int {
    $all = get_all_page_default_blocks();
    if (!isset($all[$pageSlug])) return 0;
    
    $stmt = $pdo->prepare("SELECT id FROM pages WHERE slug = ? LIMIT 1");
    $stmt->execute([$pageSlug]);
    $page = $stmt->fetch(PDO::FETCH_ASSOC);
    if (!$page) return 0;
    $pageId = (int)$page['id'];
    
    $saveStmt = $pdo->prepare("
        INSERT INTO content_blocks (page_id, block_key, block_type, content, sort_order)
        VALUES (?, ?, ?, ?, ?)
        ON DUPLICATE KEY UPDATE block_type = VALUES(block_type),
                                content    = VALUES(content),
                                sort_order = VALUES(sort_order)
    ");
    
    $count = 0;
    foreach ($all[$pageSlug] as [$key, $type, $content, $sort]) {
        $saveStmt->execute([$pageId, $key, $type, $content, $sort]);
        $count++;
    }
    return $count;
}


